"""Cleaning steps as data.

apply_steps() runs them; render_clean_py() writes a re-runnable script.
"""

from __future__ import annotations

import json
from collections.abc import Callable

import pandas as pd


def _drop_columns(df: pd.DataFrame, columns: list[str]) -> pd.DataFrame:
    return df.drop(columns=[c for c in columns if c in df.columns])


def _drop_duplicates(df: pd.DataFrame) -> pd.DataFrame:
    return df.drop_duplicates().reset_index(drop=True)


def _fill_missing(
    df: pd.DataFrame, column: str, strategy: str = "median", value=None
) -> pd.DataFrame:
    if column not in df.columns:
        return df
    s = df[column]
    if strategy == "median":
        fill = s.median()
    elif strategy == "mode":
        mode = s.mode(dropna=True)
        fill = mode.iloc[0] if not mode.empty else value
    elif strategy == "constant":
        fill = value
    else:
        raise ValueError(f"unknown fill strategy {strategy!r}")
    if fill is None:
        return df
    out = df.copy()
    out[column] = s.fillna(fill)
    return out


def _drop_rows_missing_target(df: pd.DataFrame, target: str) -> pd.DataFrame:
    return df.dropna(subset=[target]).reset_index(drop=True)


def _normalise_categories(df: pd.DataFrame, column: str) -> pd.DataFrame:
    if column not in df.columns:
        return df
    s = df[column]
    if not (s.dtype == "object" or s.dtype.name == "string"):
        return df
    out = df.copy()
    s = out[column]
    out[column] = s.where(s.isna(), s.astype(str).str.strip().str.lower())
    return out


def _clip_outliers(df: pd.DataFrame, column: str, lower: float, upper: float) -> pd.DataFrame:
    if column not in df.columns:
        return df
    out = df.copy()
    out[column] = out[column].clip(lower=lower, upper=upper)
    return out


def _coerce_numeric(df: pd.DataFrame, column: str) -> pd.DataFrame:
    if column not in df.columns:
        return df
    out = df.copy()
    out[column] = pd.to_numeric(out[column], errors="coerce")
    return out


OPS: dict[str, Callable[..., pd.DataFrame]] = {
    "drop_columns": _drop_columns,
    "drop_duplicates": _drop_duplicates,
    "fill_missing": _fill_missing,
    "drop_rows_missing_target": _drop_rows_missing_target,
    "normalise_categories": _normalise_categories,
    "clip_outliers": _clip_outliers,
    "coerce_numeric": _coerce_numeric,
}


def apply_steps(df: pd.DataFrame, steps: list[dict]) -> pd.DataFrame:
    if not steps:
        return df.copy()
    out = df
    for step in steps:
        op = step.get("op")
        if op not in OPS:
            raise ValueError(f"unknown cleaning op {op!r}")
        out = OPS[op](out, **step.get("params", {}))
    return out


def describe_step(step: dict) -> str:
    op = step.get("op")
    p = step.get("params", {})
    if op == "drop_columns":
        return "drop column(s) " + ", ".join(f"`{c}`" for c in p.get("columns", []))
    if op == "drop_duplicates":
        return "drop exact duplicate rows"
    if op == "fill_missing":
        return f"fill missing values in `{p.get('column')}` with the {p.get('strategy')}"
    if op == "drop_rows_missing_target":
        return f"drop rows where `{p.get('target')}` is missing"
    if op == "normalise_categories":
        return f"trim whitespace and lower-case the categories in `{p.get('column')}`"
    if op == "clip_outliers":
        lower, upper = p.get("lower"), p.get("upper")
        if lower is None or upper is None:
            return f"clip `{p.get('column')}` to its typical range"
        return f"clip `{p.get('column')}` to the range {lower:.4g} to {upper:.4g}"
    if op == "coerce_numeric":
        return f"convert `{p.get('column')}` to numbers (non-numeric entries become missing)"
    return f"{op} {p}"


CLEAN_PY_TEMPLATE = '''"""Generated by mlagent.

The cleaning steps approved for this project, re-runnable on new data.
"""

import json

import pandas as pd

from mlagent.cleaning import apply_steps

STEPS = json.loads(r"""__STEPS__""")


def clean(df: pd.DataFrame) -> pd.DataFrame:
    return apply_steps(df, STEPS)


if __name__ == "__main__":
    import sys

    src, dst = sys.argv[1], sys.argv[2]
    clean(pd.read_csv(src)).to_csv(dst, index=False)
'''


def render_clean_py(steps: list[dict]) -> str:
    return CLEAN_PY_TEMPLATE.replace("__STEPS__", json.dumps(steps, indent=2))
