"""Apply the image drops you approved. Generated by mlagent; safe to edit.

Run it from the project folder:

    python clean.py

Reads the raw `data.npz` / `manifest.csv` pair named in `data_meta.json`, drops the
approved image indices, and writes `data/clean/data.npz`, `data/clean/manifest.csv`,
`profile_clean.json` (a before/after summary) and
`plots/clean_before_after_classes.png`. Editing `STEPS` and rerunning is the supported
way to redo the cleaning differently; the raw pair is never modified.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# --- settings ---
SCRIPT_NAME = "clean.py"
PROJECT_DIR = Path(".")
META_FILE = "data_meta.json"
RAW_FILE = "data.npz"
MANIFEST_FILE = "manifest.csv"
CLEAN_DIR = Path("data") / "clean"
PROFILE_FILE = "profile_clean.json"
FIGURE_NAME = "clean_before_after_classes"

# --- the steps mlagent recorded ---
# Each step is {"op": "drop_indices", "params": {"indices": [...], "reason": "..."}} and
# runs against the *raw* indices. Edit and rerun freely.
STEPS_JSON = r"""[]"""
STEPS: list[dict] = json.loads(STEPS_JSON)

# --- captions ---
# Byte-identical to the matching entry in mlagent/captions.py
# (tests/test_cleaning_images.py checks this); kept here too since this script never
# depends on the mlagent package.
CAPTIONS = {
    "clean_before_after_classes": (
        "How many images each class has before and after cleaning. Bars that shrink lost "
        "duplicate or blank images; a bar that disappears means the class has no images "
        "left, which the assistant treats as an error rather than a smaller dataset."
    ),
}

# --- palette ---
SERIES = ["#2a78d6", "#eb6834", "#1baf7a", "#eda100", "#e87ba4", "#008300", "#4a3aa7", "#e34948"]
INK, INK_2, MUTED, GRID, AXIS, SURFACE = (
    "#0b0b0b", "#52514e", "#898781", "#e1e0d9", "#c3c2b7", "#fcfcfb",
)


# --- reading and writing the pair ---
def read_pair(directory: Path):
    with np.load(directory / RAW_FILE) as data:
        images = np.asarray(data["images"], dtype=np.uint8)
        labels = np.asarray(data["labels"], dtype=np.int64)
        class_names = [str(v) for v in data["class_names"].tolist()]
    manifest = pd.read_csv(directory / MANIFEST_FILE)
    return images, labels, class_names, manifest


def write_pair(directory: Path, images, labels, class_names, manifest) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        directory / RAW_FILE,
        images=np.ascontiguousarray(images, dtype=np.uint8),
        labels=np.asarray(labels, dtype=np.int64),
        class_names=np.asarray(class_names, dtype="U"),
    )
    manifest.to_csv(directory / MANIFEST_FILE, index=False, encoding="utf-8")


# --- cleaning operations ---
def dropped_indices(steps: list[dict] | None = None) -> list[int]:
    """Every image index the approved steps drop, de-duplicated and sorted."""
    steps = STEPS if steps is None else steps
    dropped: set[int] = set()
    for step in steps:
        op = step.get("op")
        if op != "drop_indices":
            raise ValueError(f"unknown image cleaning op {op!r}")
        dropped.update(int(i) for i in (step.get("params") or {}).get("indices", []))
    return sorted(dropped)


def clean(images, labels, manifest, steps: list[dict] | None = None):
    """Return (images, labels, manifest) with the approved indices removed."""
    drop = set(dropped_indices(steps))
    keep = [i for i in range(len(labels)) if i not in drop]
    kept_manifest = manifest.iloc[keep].copy().reset_index(drop=True)
    kept_manifest["index"] = range(len(kept_manifest))
    return images[keep], labels[keep], kept_manifest


# --- before and after summary ---
def summarise(images, labels, class_names) -> dict:
    counts = {name: 0 for name in class_names}
    for label in np.asarray(labels).tolist():
        if 0 <= int(label) < len(class_names):
            counts[class_names[int(label)]] += 1
    return {
        "n_images": int(len(labels)),
        "image_size": int(images.shape[1]) if images.ndim == 4 else 0,
        "n_channels": int(images.shape[3]) if images.ndim == 4 else 0,
        "n_classes": len(class_names),
        "class_counts": counts,
    }


# --- figure ---
def before_after_classes(before: dict, after: dict):
    names = list(before["class_counts"])
    y = np.arange(len(names))
    b = [before["class_counts"][n] for n in names]
    a = [after["class_counts"].get(n, 0) for n in names]
    fig = plt.figure(figsize=(6, 0.45 * max(3, len(names)) + 1.4), facecolor=SURFACE)
    ax = fig.add_subplot(111)
    ax.barh(y - 0.18, b, height=0.34, color=SERIES[0], label="before cleaning")
    ax.barh(y + 0.18, a, height=0.34, color=SERIES[1], label="after cleaning")
    ax.set_yticks(y)
    ax.set_yticklabels(names, fontsize=8, color=INK_2)
    ax.set_xlabel("images", color=MUTED, fontsize=8)
    ax.invert_yaxis()
    ax.set_facecolor(SURFACE)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    for side in ("left", "bottom"):
        ax.spines[side].set_color(AXIS)
    ax.tick_params(colors=MUTED, labelsize=8)
    ax.xaxis.grid(True, color=GRID, linewidth=0.8)
    ax.set_axisbelow(True)
    ax.set_title("Images per class before and after cleaning", color=INK, fontsize=10,
                 loc="left")
    ax.legend(frameon=False, fontsize=8, labelcolor=INK_2)
    fig.tight_layout()
    return fig


def show(fig, kind: str) -> None:
    """Display in a notebook if one is running, then print how to read the figure."""
    try:
        from IPython import get_ipython
        from IPython.display import display
    except ImportError:
        pass
    else:
        if get_ipython() is not None:
            display(fig)
    caption = CAPTIONS.get(kind, "")
    if caption:
        print("How to read this: " + caption.replace("[[", "").replace("]]", ""))


def save(fig, plots_dir: Path, name: str, kind: str) -> str:
    plots_dir.mkdir(parents=True, exist_ok=True)
    fig.savefig(plots_dir / f"{name}.png", dpi=110, bbox_inches="tight", facecolor=SURFACE)
    show(fig, kind)
    plt.close(fig)
    return f"{name}.png"


# --- command line ---
def cli_argv() -> list[str]:
    """Arguments when run as a script or via `%run`; nothing under a bare kernel cell.

    A Jupyter/Colab kernel sets `sys.argv[0]` to its own launcher (e.g.
    `ipykernel_launcher.py` or Colab's `colab_kernel_launcher.py`), which also ends in
    `.py`, so checking the extension alone would treat the kernel's own
    `-f <connection-file>.json` flags as ours and crash `argparse`.
    """
    name = Path(sys.argv[0]).name.lower() if sys.argv else ""
    return sys.argv[1:] if name == SCRIPT_NAME.lower() else []


def main(argv: list[str] | None = None) -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    parser = argparse.ArgumentParser(description="Apply the approved image drops.")
    parser.add_argument("--project", default=str(PROJECT_DIR))
    args = parser.parse_args(argv)
    project_dir = Path(args.project).resolve()

    meta_path = project_dir / META_FILE
    meta = json.loads(meta_path.read_text(encoding="utf-8")) if meta_path.exists() else {}
    raw_dir = (project_dir / str(meta.get("raw_path") or "data/raw/data.npz")).parent
    images, labels, class_names, manifest = read_pair(raw_dir)

    before = summarise(images, labels, class_names)
    kept_images, kept_labels, kept_manifest = clean(images, labels, manifest)
    after = summarise(kept_images, kept_labels, class_names)
    write_pair(project_dir / CLEAN_DIR, kept_images, kept_labels, class_names, kept_manifest)

    figures = [save(before_after_classes(before, after), project_dir / "plots", FIGURE_NAME,
                    FIGURE_NAME)]
    (project_dir / PROFILE_FILE).write_text(
        json.dumps({"before": before, "after": after, "steps": STEPS, "figures": figures},
                   indent=2, sort_keys=True),
        encoding="utf-8",
    )
    print(
        f"cleaned {before['n_images']} -> {after['n_images']} images after "
        f"{len(STEPS)} step(s) -> {(CLEAN_DIR / RAW_FILE).as_posix()}",
        flush=True,
    )
    return 0


if __name__ == "__main__":
    code = main(cli_argv())
    if code:
        sys.exit(code)
