"""Profile an image dataset and draw its four overview figures. Generated by mlagent;
safe to edit.

Run it from the project folder:

    python profile.py                                      profile the raw images
    python profile.py --input data/clean/data.npz --tag clean

Reads the `data.npz` / `manifest.csv` pair, writes `profile_{tag}.json` and PNGs into
`plots/`. Imports only numpy, pandas and matplotlib, so you can run it anywhere the
project folder exists.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# --- settings ---
SCRIPT_NAME = "profile.py"
PROJECT_DIR = Path(".")
META_FILE = "data_meta.json"
MANIFEST_FILE = "manifest.csv"
TAG = "raw"
INPUT = None  # None means "the raw .npz named in data_meta.json"
BLANK_STD_THRESHOLD = 3.0   # matches mlagent/imageset.py
THUMBS_PER_CLASS = 4
MAX_THUMB_CLASSES = 10
INTENSITY_BINS = 32

# --- captions ---
# Byte-identical to the matching entries in mlagent/captions.py
# (tests/test_template_profile_images.py checks this); kept here too since this script
# never depends on the mlagent package.
CAPTIONS = {
    "thumbnails": (
        "A few example images from each class, labelled with the class they belong to. "
        "Check the pictures really show what the label says, and that the size you chose "
        "still leaves the thing you care about visible."
    ),
    "class_balance": (
        "How many rows carry each label. A large gap between the bars is [[class imbalance]]: "
        "a model can score well just by always predicting the biggest class, so accuracy alone "
        "will flatter it."
    ),
    "intensity": (
        "How bright the red, green and blue channels are across the whole dataset, from 0 "
        "(black) to 255 (white). A spike hard against one end means many images are blown "
        "out or nearly black; three curves lying on top of each other means the pictures "
        "are effectively greyscale."
    ),
    "class_means": (
        "The average of every image in one class. A mean image that still shows a clear "
        "shape means that class looks consistent, so it is easy to learn; a formless blur "
        "means the object moves around the frame, which is harder but more realistic."
    ),
}

# --- palette ---
SERIES = ["#2a78d6", "#eb6834", "#1baf7a", "#eda100", "#e87ba4", "#008300", "#4a3aa7", "#e34948"]
INK, INK_2, MUTED, GRID, AXIS, SURFACE = (
    "#0b0b0b", "#52514e", "#898781", "#e1e0d9", "#c3c2b7", "#fcfcfb",
)


def style(ax, title=None, grid_axis="y"):
    ax.set_facecolor(SURFACE)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    for side in ("left", "bottom"):
        ax.spines[side].set_color(AXIS)
    ax.tick_params(colors=MUTED, labelsize=8)
    ax.grid(False)
    if grid_axis in ("y", "both"):
        ax.yaxis.grid(True, color=GRID, linewidth=0.8)
    if grid_axis in ("x", "both"):
        ax.xaxis.grid(True, color=GRID, linewidth=0.8)
    ax.set_axisbelow(True)
    if title:
        ax.set_title(title, color=INK, fontsize=10, loc="left")


# --- reading the data ---
def read_json(path: Path, default=None):
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def load_pair(project_dir: Path, input_path: str | None, meta: dict):
    """(images, labels, class_names, manifest, path) from the .npz plus its manifest.csv."""
    relative = input_path or meta.get("raw_path") or "data/raw/data.npz"
    path = project_dir / relative
    if not path.exists():
        raise FileNotFoundError(f"no image file at {path}")
    with np.load(path) as data:
        images = np.asarray(data["images"], dtype=np.uint8)
        labels = np.asarray(data["labels"], dtype=np.int64)
        class_names = [str(v) for v in data["class_names"].tolist()]
    manifest_path = path.parent / MANIFEST_FILE
    manifest = pd.read_csv(manifest_path) if manifest_path.exists() else pd.DataFrame()
    return images, labels, class_names, manifest, path


# --- describing the images ---
def count_duplicates(images: np.ndarray) -> int:
    """How many images are an exact copy of an earlier one (by content hash)."""
    seen: dict[str, int] = defaultdict(int)
    for image in images:
        seen[hashlib.sha1(np.ascontiguousarray(image).tobytes()).hexdigest()] += 1
    return int(sum(count - 1 for count in seen.values() if count > 1))


def count_blanks(images: np.ndarray) -> int:
    if images.size == 0:
        return 0
    stds = images.reshape(images.shape[0], -1).astype(np.float32).std(axis=1)
    return int((stds < BLANK_STD_THRESHOLD).sum())


def size_stats(series: pd.Series) -> dict:
    if series.empty:
        return {"min": None, "median": None, "max": None}
    values = pd.to_numeric(series, errors="coerce").dropna()
    if values.empty:
        return {"min": None, "median": None, "max": None}
    return {
        "min": int(values.min()),
        "median": int(round(float(values.median()))),
        "max": int(values.max()),
    }


def profile_images(images, labels, class_names, manifest) -> dict:
    counts = {name: 0 for name in class_names}
    for label in labels.tolist():
        if 0 <= int(label) < len(class_names):
            counts[class_names[int(label)]] += 1
    flat = images.reshape(-1, images.shape[3]).astype(np.float32) if images.size else None
    return {
        "n_images": int(images.shape[0]),
        "image_size": int(images.shape[1]) if images.ndim == 4 else 0,
        "n_channels": int(images.shape[3]) if images.ndim == 4 else 0,
        "n_classes": len(class_names),
        "class_counts": counts,
        "duplicate_images": count_duplicates(images),
        "blank_images": count_blanks(images),
        "channel_mean": [round(float(v), 4) for v in flat.mean(axis=0)] if flat is not None
        else [],
        "channel_std": [round(float(v), 4) for v in flat.std(axis=0)] if flat is not None
        else [],
        "source_width": size_stats(manifest.get("source_width", pd.Series(dtype=float))),
        "source_height": size_stats(manifest.get("source_height", pd.Series(dtype=float))),
    }


# --- figures ---
def show(fig, kind: str) -> None:
    """Display in a notebook if one is running, then print how to read the figure."""
    try:
        from IPython import get_ipython
        from IPython.display import display
    except ImportError:
        pass
    else:
        if get_ipython() is not None:
            display(fig)
    caption = CAPTIONS.get(kind, "")
    if caption:
        print("How to read this: " + caption.replace("[[", "").replace("]]", ""))


def save(fig, plots_dir: Path, name: str, kind: str) -> str:
    plots_dir.mkdir(parents=True, exist_ok=True)
    fig.savefig(plots_dir / f"{name}.png", dpi=110, bbox_inches="tight", facecolor=SURFACE)
    show(fig, kind)
    plt.close(fig)
    return f"{name}.png"


def thumbnails(images, labels, class_names):
    shown = class_names[:MAX_THUMB_CLASSES]
    nrows = max(1, len(shown))
    fig, axes = plt.subplots(nrows, THUMBS_PER_CLASS,
                             figsize=(1.6 * THUMBS_PER_CLASS, 1.7 * nrows),
                             facecolor=SURFACE, squeeze=False)
    for row, name in enumerate(shown):
        picks = np.flatnonzero(labels == class_names.index(name))[:THUMBS_PER_CLASS]
        for col in range(THUMBS_PER_CLASS):
            ax = axes[row][col]
            ax.set_xticks([])
            ax.set_yticks([])
            for side in ("top", "right", "left", "bottom"):
                ax.spines[side].set_color(AXIS)
            if col < len(picks):
                ax.imshow(images[int(picks[col])])
            else:
                ax.set_facecolor(SURFACE)
            if col == 0:
                ax.set_ylabel(name, color=INK_2, fontsize=8, rotation=0,
                              ha="right", va="center", labelpad=8)
    fig.suptitle("Example images per class", color=INK, fontsize=11, x=0.01, ha="left")
    fig.tight_layout()
    return fig


def class_balance(counts: dict):
    fig = plt.figure(figsize=(5, 0.5 * max(3, len(counts)) + 1.2), facecolor=SURFACE)
    ax = fig.add_subplot(111)
    labels = [str(k) for k in counts]
    values = [int(v) for v in counts.values()]
    denom = sum(values) or 1
    ax.barh(labels, values, color=SERIES[0], height=0.6)
    for i, v in enumerate(values):
        ax.text(v, i, f"  {v} ({v / denom:.0%})", va="center", color=INK_2, fontsize=8)
    style(ax, "Images per class", grid_axis="x")
    ax.invert_yaxis()
    ax.set_xlim(0, max(values) * 1.3 if values else 1)
    fig.tight_layout()
    return fig


def intensity(images):
    fig = plt.figure(figsize=(6, 3.0), facecolor=SURFACE)
    ax = fig.add_subplot(111)
    names = ("red", "green", "blue")
    for channel in range(min(3, images.shape[3] if images.ndim == 4 else 0)):
        values = images[:, :, :, channel].reshape(-1)
        ax.hist(values, bins=INTENSITY_BINS, range=(0, 255), histtype="step",
                linewidth=2, color=SERIES[channel], label=names[channel])
    style(ax, "Pixel intensity per channel")
    ax.set_xlabel("intensity (0 = black, 255 = white)", color=MUTED, fontsize=8)
    ax.legend(frameon=False, fontsize=8, labelcolor=INK_2)
    fig.tight_layout()
    return fig


def class_means(images, labels, class_names):
    shown = class_names[:MAX_THUMB_CLASSES]
    n = max(1, len(shown))
    ncols = min(5, n)
    nrows = int(np.ceil(n / ncols))
    fig, axes = plt.subplots(nrows, ncols, figsize=(1.8 * ncols, 2.0 * nrows),
                             facecolor=SURFACE, squeeze=False)
    for ax in axes.flat:
        ax.set_xticks([])
        ax.set_yticks([])
        ax.set_visible(False)
    for i, name in enumerate(shown):
        ax = axes[i // ncols][i % ncols]
        ax.set_visible(True)
        picks = np.flatnonzero(labels == class_names.index(name))
        if picks.size:
            ax.imshow(images[picks].astype(np.float32).mean(axis=0).astype(np.uint8))
        ax.set_title(name, color=INK, fontsize=9, loc="left")
    fig.suptitle("Mean image per class", color=INK, fontsize=11, x=0.01, ha="left")
    fig.tight_layout()
    return fig


def draw_all(images, labels, class_names, profile: dict, plots_dir: Path, tag: str):
    return [
        save(thumbnails(images, labels, class_names), plots_dir, f"{tag}_thumbnails",
             "thumbnails"),
        save(class_balance(profile["class_counts"]), plots_dir, f"{tag}_class_balance",
             "class_balance"),
        save(intensity(images), plots_dir, f"{tag}_intensity", "intensity"),
        save(class_means(images, labels, class_names), plots_dir, f"{tag}_class_means",
             "class_means"),
    ]


# --- command line ---
def cli_argv() -> list[str]:
    """Arguments when run as a script or via `%run`; nothing under a bare kernel cell.

    A Jupyter/Colab kernel sets `sys.argv[0]` to its own launcher (e.g.
    `ipykernel_launcher.py` or Colab's `colab_kernel_launcher.py`), which also ends in
    `.py`, so checking the extension alone would treat the kernel's own
    `-f <connection-file>.json` flags as ours and crash `argparse`.
    """
    name = Path(sys.argv[0]).name.lower() if sys.argv else ""
    return sys.argv[1:] if name == SCRIPT_NAME.lower() else []


def main(argv: list[str] | None = None) -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    parser = argparse.ArgumentParser(description="Profile an image dataset and draw figures.")
    parser.add_argument("--project", default=str(PROJECT_DIR))
    parser.add_argument("--input", default=INPUT, help=".npz path relative to --project")
    parser.add_argument("--tag", default=TAG, help="prefix for the output files")
    args = parser.parse_args(argv)

    project_dir = Path(args.project).resolve()
    meta = read_json(project_dir / META_FILE, default={}) or {}
    images, labels, class_names, manifest, path = load_pair(project_dir, args.input, meta)
    profile = profile_images(images, labels, class_names, manifest)
    profile["figures"] = draw_all(images, labels, class_names, profile,
                                  project_dir / "plots", args.tag)
    out = project_dir / f"profile_{args.tag}.json"
    out.write_text(json.dumps(profile, indent=2, sort_keys=True), encoding="utf-8")
    print(
        f"profiled {path.name}: {profile['n_images']} images at "
        f"{profile['image_size']}px across {profile['n_classes']} classes "
        f"-> {out.name} and {len(profile['figures'])} figures",
        flush=True,
    )
    return 0


if __name__ == "__main__":
    code = main(cli_argv())
    if code:
        sys.exit(code)
