"""Load the cleaned images and split them. Generated by mlagent; safe to edit.

Reads `data_meta.json` (class labels, split fractions, image size) and the clean
`data.npz` / `manifest.csv` pair. Pixels are scaled to float32 [0, 1] and normalised per
channel using the training split's own mean and standard deviation, so validation and
test never see a statistic computed from themselves.

The train/val/test split is seeded from `data_meta.json`'s `split_seed` (default 42),
never from `config.json`, so the held-out test split is the same for every run and a
checkpoint's validation numbers stay comparable across tuning. `config.json`'s `seed`
only seeds the model and the augmentation (see `model.py` and `augment_batch`).

Run `python data.py` on its own to print the split sizes without training anything.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import torch
from torch.utils.data import DataLoader, TensorDataset

# --- settings ---
SCRIPT_NAME = "data.py"
PROJECT_DIR = Path(".")
META_FILE = "data_meta.json"
DEFAULT_SPLIT_SEED = 42
MAX_SHIFT_FRACTION = 0.1   # "basic" augmentation shifts by up to this share of the width
EPS = 1e-6


# --- loading ---
def read_meta(project_dir: Path) -> dict:
    return json.loads((project_dir / META_FILE).read_text(encoding="utf-8"))


def load_pair(path: Path):
    """(images uint8 (N, H, W, 3), labels int64 (N,), class_names) from one .npz."""
    with np.load(path) as data:
        images = np.asarray(data["images"], dtype=np.uint8)
        labels = np.asarray(data["labels"], dtype=np.int64)
        class_names = [str(v) for v in data["class_names"].tolist()]
    return images, labels, class_names


# --- splitting ---
def stratified_split(labels: np.ndarray, splits: dict, seed: int) -> dict[str, np.ndarray]:
    """Index arrays for train/val/test, each class split in the same proportions.

    A class with fewer than 3 images cannot supply a non-empty val and test slice as
    well as a non-empty train slice, so it goes entirely to train (with a warning)
    rather than risk an empty val/test slice for that class.
    """
    rng = np.random.default_rng(int(seed))
    train_frac = float(splits["train"])
    val_frac = float(splits["val"])
    chosen: dict[str, list[int]] = {"train": [], "val": [], "test": []}
    for label in sorted(set(labels.tolist())):
        idx = np.flatnonzero(labels == label)
        rng.shuffle(idx)
        n = len(idx)
        if n < 3:
            print(f"warning: class {label} has only {n} image(s); keeping all of it in train",
                  flush=True)
            chosen["train"].extend(idx.tolist())
            continue
        n_train = max(1, int(round(train_frac * n)))
        n_val = max(1, int(round(val_frac * n)))
        if n_train + n_val >= n:
            n_train = max(1, n - 2)
            n_val = 1
        chosen["train"].extend(idx[:n_train].tolist())
        chosen["val"].extend(idx[n_train:n_train + n_val].tolist())
        chosen["test"].extend(idx[n_train + n_val:].tolist())
    return {name: np.array(sorted(values), dtype=np.int64) for name, values in chosen.items()}


# --- tensors ---
def to_tensor(images: np.ndarray) -> torch.Tensor:
    """uint8 (N, H, W, 3) -> float32 (N, 3, H, W) in [0, 1]."""
    array = np.asarray(images, dtype=np.float32) / 255.0
    return torch.from_numpy(array).permute(0, 3, 1, 2).contiguous()


def channel_stats(x: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
    mean = x.mean(dim=(0, 2, 3))
    std = x.std(dim=(0, 2, 3)).clamp_min(EPS)
    return mean, std


def normalise(x: torch.Tensor, mean: torch.Tensor, std: torch.Tensor) -> torch.Tensor:
    return (x - mean.view(1, -1, 1, 1)) / std.view(1, -1, 1, 1)


def load_data(project_dir: Path | str, config: dict) -> dict:
    project_dir = Path(project_dir)
    meta = read_meta(project_dir)
    path = project_dir / str(meta.get("clean_path") or "data/clean/data.npz")
    images, labels, class_names = load_pair(path)
    class_names = [str(c) for c in (meta.get("class_labels") or class_names)]
    splits = meta["splits"]
    seed = int(meta.get("split_seed", DEFAULT_SPLIT_SEED))
    parts = stratified_split(labels, splits, seed)

    x_all = to_tensor(images)
    y_all = torch.from_numpy(labels).to(torch.int64)
    mean, std = channel_stats(x_all[parts["train"]])
    data: dict = {}
    for name in ("train", "val", "test"):
        idx = torch.from_numpy(parts[name])
        data[name] = (normalise(x_all[idx], mean, std), y_all[idx])
        data[f"n_{name}"] = int(idx.numel())
    data.update({
        "classes": class_names,
        "task_type": str(meta.get("task_type", "image_classification")),
        "image_size": int(x_all.shape[2]),
        "n_channels": int(x_all.shape[1]),
        "channel_mean": [round(float(v), 6) for v in mean.tolist()],
        "channel_std": [round(float(v), 6) for v in std.tolist()],
    })
    validate(data)
    return data


# --- loaders and augmentation ---
def make_loader(pair, batch_size: int, shuffle: bool, seed: int = 0) -> DataLoader:
    x, y = pair
    generator = torch.Generator().manual_seed(int(seed))
    return DataLoader(
        TensorDataset(x, y), batch_size=max(1, int(batch_size)), shuffle=bool(shuffle),
        generator=generator if shuffle else None, drop_last=False,
    )


def shift_batch(x: torch.Tensor, dy: int, dx: int) -> torch.Tensor:
    """Shift every image in the batch by `(dy, dx)` pixels, padding with zeros.

    Unlike `torch.roll`, pixels that leave one edge are dropped, not wrapped onto the
    opposite edge: the output is zero-padded then cropped back to the input size.
    """
    height, width = x.shape[2], x.shape[3]
    pad = max(abs(int(dy)), abs(int(dx)), 1)
    padded = torch.nn.functional.pad(x, (pad, pad, pad, pad))
    top = pad - int(dy)
    left = pad - int(dx)
    return padded[:, :, top:top + height, left:left + width]


def augment_batch(x: torch.Tensor, generator: torch.Generator) -> torch.Tensor:
    """Random horizontal flip plus a small random pad-and-crop shift, in plain tensor ops.

    `shift_batch` pads with zeros and crops rather than wrapping, so a pixel shifted off
    one edge is gone, not glued onto the opposite edge.

    No torchvision: the two cheap CNN families must run wherever torch does.
    """
    flip = torch.rand(x.shape[0], generator=generator) < 0.5
    out = x.clone()
    out[flip] = torch.flip(out[flip], dims=[3])
    limit = max(1, int(round(MAX_SHIFT_FRACTION * x.shape[3])))
    dy = int(torch.randint(-limit, limit + 1, (1,), generator=generator).item())
    dx = int(torch.randint(-limit, limit + 1, (1,), generator=generator).item())
    return shift_batch(out, dy, dx)


def pick_device() -> str:
    return "cuda" if torch.cuda.is_available() else "cpu"


# --- validation ---
def validate(data: dict) -> None:
    """Raise ValueError if the splits are unusable: empty, overlapping, or one class."""
    for name in ("train", "val", "test"):
        if data[f"n_{name}"] == 0:
            raise ValueError(f"the {name} split is empty; adjust the split fractions")
    if len(torch.unique(data["train"][1])) < 2:
        raise ValueError("training split contains fewer than 2 classes")
    if len(data["classes"]) < 2:
        raise ValueError("data_meta.json lists fewer than 2 classes")


# --- command line ---
def cli_argv() -> list[str]:
    """Arguments when run as a script or via `%run`; nothing under a bare kernel cell.

    A Jupyter/Colab kernel sets `sys.argv[0]` to its own launcher (e.g.
    `ipykernel_launcher.py` or Colab's `colab_kernel_launcher.py`), which also ends in
    `.py`, so checking the extension alone would treat the kernel's own
    `-f <connection-file>.json` flags as ours and crash `argparse`.
    """
    name = Path(sys.argv[0]).name.lower() if sys.argv else ""
    return sys.argv[1:] if name == SCRIPT_NAME.lower() else []


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Report the image splits without training.")
    parser.add_argument("--project", default=str(PROJECT_DIR))
    args = parser.parse_args(argv)
    project_dir = Path(args.project).resolve()
    config_path = project_dir / "config.json"
    config = json.loads(config_path.read_text(encoding="utf-8")) if config_path.exists() else {}
    data = load_data(project_dir, config)
    print(
        f"train {data['n_train']} / val {data['n_val']} / test {data['n_test']} images at "
        f"{data['image_size']}px across {len(data['classes'])} classes",
        flush=True,
    )
    return 0


if __name__ == "__main__":
    code = main(cli_argv())
    if code:
        sys.exit(code)
