"""Build the network. Generated by mlagent; safe to edit.

Three families, all returning a plain `torch.nn.Module` that maps a (N, 3, H, W) batch to
(N, n_classes) logits:

- tiny_cnn:  two convolutional blocks. Fast, and enough for simple shapes.
- small_cnn: three convolutional blocks with batch norm and dropout.
- resnet18:  a deeper transfer-learning network, optionally starting from ImageNet
             weights. Its extra dependency is imported *inside* the builder function,
             never at module scope, so a tiny_cnn or small_cnn run never needs it
             installed (see `_resnet18` below).
"""

from __future__ import annotations

import torch
from torch import nn

# --- settings ---
MODEL_TYPES = ("tiny_cnn", "small_cnn", "resnet18")
RESNET_MIN_SIZE = 32


# --- the two hand-built CNNs ---
def _block(in_channels: int, out_channels: int, batch_norm: bool) -> list[nn.Module]:
    layers: list[nn.Module] = [nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1)]
    if batch_norm:
        layers.append(nn.BatchNorm2d(out_channels))
    layers += [nn.ReLU(inplace=True), nn.MaxPool2d(2)]
    return layers


class TinyCNN(nn.Module):
    """Two convolutional blocks, then a linear head."""

    def __init__(self, n_classes: int, dropout: float = 0.3):
        super().__init__()
        self.features = nn.Sequential(
            *_block(3, 16, batch_norm=False),
            *_block(16, 32, batch_norm=False),
        )
        self.pool = nn.AdaptiveAvgPool2d(1)
        self.head = nn.Sequential(nn.Flatten(), nn.Dropout(float(dropout)),
                                  nn.Linear(32, int(n_classes)))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.head(self.pool(self.features(x)))


class SmallCNN(nn.Module):
    """Three convolutional blocks with batch norm, then a dropout head."""

    def __init__(self, n_classes: int, dropout: float = 0.3):
        super().__init__()
        self.features = nn.Sequential(
            *_block(3, 32, batch_norm=True),
            *_block(32, 64, batch_norm=True),
            *_block(64, 128, batch_norm=True),
        )
        self.pool = nn.AdaptiveAvgPool2d(1)
        self.head = nn.Sequential(nn.Flatten(), nn.Dropout(float(dropout)),
                                  nn.Linear(128, int(n_classes)))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.head(self.pool(self.features(x)))


# --- transfer learning ---
def _resnet18(config: dict, n_classes: int, image_size: int) -> nn.Module:
    """torchvision's ResNet-18 with a fresh final layer.

    The import lives here so tiny_cnn and small_cnn never require torchvision.
    """
    import torchvision

    if int(image_size) < RESNET_MIN_SIZE:
        raise ValueError(f"resnet18 needs images of at least {RESNET_MIN_SIZE}px")
    pretrained = str(config.get("pretrained", "imagenet")) == "imagenet"
    weights = torchvision.models.ResNet18_Weights.DEFAULT if pretrained else None
    model = torchvision.models.resnet18(weights=weights)
    if str(config.get("freeze_backbone", "no")) == "yes":
        for parameter in model.parameters():
            parameter.requires_grad = False
    model.fc = nn.Linear(model.fc.in_features, int(n_classes))
    return model


# --- building each family ---
def build_model(config: dict, n_classes: int, image_size: int) -> nn.Module:
    model_type = str(config.get("model_type", "small_cnn"))
    if model_type not in MODEL_TYPES:
        raise ValueError(f"unknown model_type {model_type!r}; expected one of {MODEL_TYPES}")
    torch.manual_seed(int(config.get("seed", 42)))
    dropout = float(config.get("dropout", 0.3))
    if model_type == "tiny_cnn":
        return TinyCNN(n_classes, dropout)
    if model_type == "small_cnn":
        return SmallCNN(n_classes, dropout)
    return _resnet18(config, n_classes, image_size)
