"""Train the network, evaluate per epoch, write metrics.json. Generated by mlagent; safe
to edit.

Usage (run from the project folder):
  python train.py                one full training run
  python train.py --dry-run      times three training batches, writes dry_run.json only

After training, run `evaluate.py` to score the saved checkpoint and draw its figures.
The checkpoint holds a `state_dict` plus the config and class names, so `evaluate.py` can
rebuild exactly the same network.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import sys
import tempfile
import time
import traceback
from datetime import datetime, timezone
from pathlib import Path

import matplotlib.pyplot as plt
import torch
from data import augment_batch, load_data, make_loader, pick_device
from evaluate import (
    HIGHER_IS_BETTER,
    INK_2,
    MUTED,
    SERIES,
    SURFACE,
    evaluate_split,
    frame,
    metric_for,
)
from model import build_model
from torch import nn

# --- settings ---
SCRIPT_NAME = "train.py"
CONFIG_FILE = "config.json"
METRICS_FILE = "metrics.json"
CHECKPOINT = Path("checkpoints") / "best.pt"
CHECKPOINT_REL = "checkpoints/best.pt"
CURVES_FIGURE = Path("plots") / "training_curves.png"
DRY_RUN_FILE = "dry_run.json"
DRY_RUN_BATCHES = 3

# --- captions ---
# Byte-identical to the matching entry in mlagent/captions.py; kept here too since this
# script never depends on the mlagent package.
CAPTIONS = {
    "training_curves": (
        "Left: [[loss]] per [[epoch]] for the training and validation splits. Right: the same "
        "for your chosen metric. Training loss falling while validation loss rises is "
        "[[overfitting]]; both flat is a [[plateau]]."
    ),
}


# --- environment ---
def prefer_stdlib_modules() -> None:
    """Make sure Python's own `profile`/`cProfile` modules win over this project's
    `profile.py` (written by the data stage, in the same folder as this script).

    Running "python train.py" puts this script's own directory first on sys.path.
    torch's optimiser internals lazily `import cProfile`, which does `import profile` for
    its stdlib docstrings; left first on sys.path, the project's profile.py would shadow
    the stdlib module and crash that import. Called before the optimiser is built.
    """
    here = os.path.dirname(os.path.abspath(sys.argv[0])) if sys.argv and sys.argv[0] else ""
    sys.path[:] = [p for p in sys.path if p not in ("", here)] + [
        p for p in sys.path if p in ("", here)
    ]


# --- small helpers ---
def read_json(path: Path, default=None):
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, obj) -> None:
    """Atomic write so a reader polling the file never sees a partial JSON document."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.", suffix=".tmp")
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(json.dumps(obj, indent=2, sort_keys=True))
    # Windows: os.replace can fail with PermissionError if a poller has the target open; retry.
    attempts = 20
    for attempt in range(attempts):
        try:
            os.replace(tmp, path)
            return
        except PermissionError:
            if attempt == attempts - 1:
                Path(tmp).unlink(missing_ok=True)
                raise
            time.sleep(0.05)


def empty_metrics() -> dict:
    """A metrics dict with all required keys and placeholder values."""
    return {
        "status": "running",
        "started_at": None,
        "model_type": None,
        "task_type": None,
        "metric": None,
        "higher_is_better": None,
        "config": None,
        "classes": None,
        "n_train": None,
        "n_val": None,
        "n_test": None,
        "epochs": [],
        "best_epoch": None,
        "best_val_metric": None,
        "stopped_early": False,
        "error": None,
        "seconds": None,
        "seconds_per_epoch": None,
        "device": None,
        "checkpoint": None,
    }


# --- the live training curve ---
_HANDLE = None
_CAPTION_PRINTED = False


def training_curves(epochs: list[dict], metric: str):
    fig, (ax_loss, ax_metric) = plt.subplots(1, 2, figsize=(9, 3.2), facecolor=SURFACE)
    xs = [e["epoch"] for e in epochs]
    panels = (
        (ax_loss, ("train_loss", "val_loss"), "Loss per epoch"),
        (ax_metric, ("train_metric", "val_metric"), f"{metric} per epoch"),
    )
    for ax, keys, title in panels:
        for key, colour, label in zip(keys, SERIES[:2], ("train", "validation"), strict=True):
            ax.plot(xs, [e.get(key) for e in epochs], color=colour, linewidth=2,
                    marker="o", markersize=4, label=label)
        frame(ax, title)
        ax.set_xlabel("epoch", color=INK_2, fontsize=8)
        ax.legend(frameon=False, fontsize=8, labelcolor=INK_2)
    if not epochs:
        ax_loss.text(0.5, 0.5, "no epochs yet", ha="center", va="center", color=MUTED,
                     transform=ax_loss.transAxes)
    fig.tight_layout()
    return fig


def redraw(fig) -> None:
    """Update one output area in place, so the curve animates instead of stacking up."""
    global _HANDLE, _CAPTION_PRINTED
    try:
        from IPython import get_ipython
        from IPython.display import display
    except ImportError:
        pass
    else:
        if get_ipython() is not None:
            if _HANDLE is None:
                _HANDLE = display(fig, display_id=True)
            else:
                _HANDLE.update(fig)
    if not _CAPTION_PRINTED:
        _CAPTION_PRINTED = True
        caption = CAPTIONS.get("training_curves", "")
        print("How to read this: " + caption.replace("[[", "").replace("]]", ""))


def draw_curves(project_dir: Path, epochs: list[dict], metric: str) -> None:
    fig = training_curves(epochs, metric)
    path = project_dir / CURVES_FIGURE
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=110, bbox_inches="tight", facecolor=SURFACE)
    redraw(fig)
    plt.close(fig)


# --- Dry run ---
def _dry_batches(loader, count: int) -> list:
    """`count` batches from the loader, cycling it when the training split is shorter."""
    batches: list = []
    while len(batches) < count:
        before = len(batches)
        for batch in loader:
            batches.append(batch)
            if len(batches) == count:
                return batches
        if len(batches) == before:
            break
    return batches


def dry_run_timing(project_dir: Path) -> dict:
    """Time three real training batches so the agent can estimate the whole run.

    The first batch is a warm-up and is not timed, so one-off costs (the first CUDA
    kernel launch, cuDNN's algorithm search, the first reads off the tensor cache) stay
    out of the number. Writes `dry_run.json` and nothing else: no metrics.json, no
    checkpoint, no figure.
    """
    config = read_json(project_dir / CONFIG_FILE, default={}) or {}
    data = load_data(project_dir, config)
    batch_size = int(config.get("batch_size", 32))
    seed = int(config.get("seed", 42))
    device = pick_device()
    torch.manual_seed(seed)
    model = build_model(config, len(data["classes"]), data["image_size"]).to(device)
    loss_fn = nn.CrossEntropyLoss()
    optimiser = torch.optim.AdamW(
        [p for p in model.parameters() if p.requires_grad],
        lr=float(config.get("learning_rate", 0.001)),
        weight_decay=float(config.get("weight_decay", 0.0001)),
    )
    loader = make_loader(data["train"], batch_size, shuffle=True, seed=seed)
    generator = torch.Generator().manual_seed(seed)
    augment = str(config.get("augment", "basic")) != "none"
    batches_per_epoch = len(loader)

    def step(batch) -> None:
        batch_x, batch_y = batch
        if augment:
            batch_x = augment_batch(batch_x, generator)
        batch_x = batch_x.to(device)
        batch_y = batch_y.to(device)
        optimiser.zero_grad(set_to_none=True)
        loss = loss_fn(model(batch_x), batch_y)
        loss.backward()
        optimiser.step()

    batches = _dry_batches(loader, DRY_RUN_BATCHES + 1)
    if not batches:
        raise ValueError("the training split has no batches to time")
    model.train()
    step(batches[0])                                   # warm-up, not timed
    if device == "cuda":
        torch.cuda.synchronize()
    started = time.time()
    for batch in batches[1:]:
        step(batch)
    if device == "cuda":
        torch.cuda.synchronize()
    elapsed = time.time() - started
    timed = max(1, len(batches) - 1)
    seconds_per_batch = round(elapsed / timed, 4)
    gpu_name = torch.cuda.get_device_name(0) if device == "cuda" else None
    record = {
        "device": device,
        "gpu_name": gpu_name,
        "batches_per_epoch": batches_per_epoch,
        "seconds_per_batch": seconds_per_batch,
        "seconds_per_epoch": round(seconds_per_batch * batches_per_epoch, 4),
        "n_train": int(data["n_train"]),
        "script": SCRIPT_NAME,
    }
    write_json(project_dir / DRY_RUN_FILE, record)
    where = f"{device} ({gpu_name})" if gpu_name else device
    print(
        f"Dry run: {timed} batches in {elapsed:.2f} s on {where}; about "
        f"{seconds_per_batch:.3f} s per batch, {batches_per_epoch} batches per epoch",
        flush=True,
    )
    return record


# --- training ---
def fit_epoch(model, loader, optimiser, loss_fn, device: str, augment: bool,
              generator) -> None:
    model.train()
    for batch_x, batch_y in loader:
        if augment:
            batch_x = augment_batch(batch_x, generator)
        batch_x = batch_x.to(device)
        batch_y = batch_y.to(device)
        optimiser.zero_grad(set_to_none=True)
        loss = loss_fn(model(batch_x), batch_y)
        loss.backward()
        optimiser.step()


def train(project_dir: Path) -> dict:
    config = read_json(project_dir / CONFIG_FILE, default={}) or {}
    data = load_data(project_dir, config)
    task_type = data["task_type"]
    metric = metric_for(project_dir, task_type)
    higher = HIGHER_IS_BETTER[metric]
    classes = data["classes"]
    n_classes = len(classes)
    epochs = int(config.get("epochs", 10))
    patience = int(config.get("early_stopping_patience", 0))
    batch_size = int(config.get("batch_size", 32))
    seed = int(config.get("seed", 42))
    device = pick_device()
    metrics_path = project_dir / METRICS_FILE

    metrics = empty_metrics()
    metrics["started_at"] = datetime.now(timezone.utc).isoformat(timespec="microseconds")
    metrics.update({
        "model_type": str(config.get("model_type", "small_cnn")),
        "task_type": task_type,
        "metric": metric,
        "higher_is_better": higher,
        "config": config,
        "classes": classes,
        "n_train": data["n_train"],
        "n_val": data["n_val"],
        "n_test": data["n_test"],
        "device": device,
    })

    def save() -> None:
        write_json(metrics_path, metrics)

    save()
    torch.manual_seed(seed)
    model = build_model(config, n_classes, data["image_size"]).to(device)
    loss_fn = nn.CrossEntropyLoss()
    optimiser = torch.optim.AdamW(
        [p for p in model.parameters() if p.requires_grad],
        lr=float(config.get("learning_rate", 0.001)),
        weight_decay=float(config.get("weight_decay", 0.0001)),
    )
    train_loader = make_loader(data["train"], batch_size, shuffle=True, seed=seed)
    generator = torch.Generator().manual_seed(seed)
    augment = str(config.get("augment", "basic")) != "none"

    best_state = None
    best_value = None
    since_best = 0
    started = time.time()
    for epoch in range(1, epochs + 1):
        t0 = time.time()
        fit_epoch(model, train_loader, optimiser, loss_fn, device, augment, generator)
        tr = evaluate_split(model, data["train"], device, metric, n_classes, batch_size)
        va = evaluate_split(model, data["val"], device, metric, n_classes, batch_size)
        row = {
            "epoch": epoch,
            "train_loss": tr["loss"],
            "val_loss": va["loss"],
            "train_metric": tr["value"],
            "val_metric": va["value"],
            "seconds": round(time.time() - t0, 3),
        }
        metrics["epochs"].append(row)
        if not (math.isfinite(row["train_loss"]) and math.isfinite(row["val_loss"])):
            metrics["status"] = "failed"
            metrics["error"] = f"non-finite loss at epoch {epoch}"
            save()
            return metrics
        improved = best_value is None or (
            row["val_metric"] > best_value if higher else row["val_metric"] < best_value
        )
        if improved:
            best_value = row["val_metric"]
            metrics["best_epoch"] = epoch
            metrics["best_val_metric"] = best_value
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            since_best = 0
        else:
            since_best += 1
        save()
        draw_curves(project_dir, metrics["epochs"], metric)
        print(
            f"epoch {epoch}/{epochs} train_loss={row['train_loss']:.4f} "
            f"val_loss={row['val_loss']:.4f} val_{metric}={row['val_metric']:.4f}",
            flush=True,
        )
        if patience and since_best >= patience:
            metrics["stopped_early"] = True
            break

    elapsed = time.time() - started
    metrics["seconds"] = round(elapsed, 3)
    metrics["seconds_per_epoch"] = round(elapsed / max(1, len(metrics["epochs"])), 4)

    (project_dir / CHECKPOINT).parent.mkdir(parents=True, exist_ok=True)
    torch.save(
        {"state_dict": best_state or model.state_dict(), "config": config,
         "classes": classes, "image_size": data["image_size"]},
        project_dir / CHECKPOINT,
    )
    metrics["checkpoint"] = CHECKPOINT_REL
    metrics["status"] = "done"
    save()
    return metrics


# --- command line ---
def cli_argv() -> list[str]:
    """Arguments when run as a script or via `%run`; nothing under a bare kernel cell.

    A Jupyter/Colab kernel sets `sys.argv[0]` to its own launcher (e.g.
    `ipykernel_launcher.py` or Colab's `colab_kernel_launcher.py`), which also ends in
    `.py`, so checking the extension alone would treat the kernel's own
    `-f <connection-file>.json` flags as ours and crash `argparse`.
    """
    name = Path(sys.argv[0]).name.lower() if sys.argv else ""
    return sys.argv[1:] if name == SCRIPT_NAME.lower() else []


def main(argv: list[str] | None = None) -> int:
    prefer_stdlib_modules()
    parser = argparse.ArgumentParser(description="Train the network and record every epoch.")
    parser.add_argument("--project", default=".", help="project folder (default: cwd)")
    parser.add_argument("--dry-run", action="store_true",
                        help="time three training batches and write dry_run.json only")
    args = parser.parse_args(argv)
    project_dir = Path(args.project).resolve()
    if args.dry_run:
        try:
            dry_run_timing(project_dir)
        except Exception as exc:  # noqa: BLE001 - the agent reads the exit code and stderr
            traceback.print_exc()
            print(f"error: {exc}", file=sys.stderr, flush=True)
            return 1
        return 0
    try:
        # Fresh placeholders before training starts, so a failure before the first save()
        # cannot leave a previous run's epochs or best metric on disk.
        write_json(project_dir / METRICS_FILE, empty_metrics())
        metrics = train(project_dir)
        return 0 if metrics["status"] != "failed" else 1
    except Exception as exc:  # noqa: BLE001 - record any failure for the debrief
        traceback.print_exc()
        existing = {**empty_metrics(),
                    **(read_json(project_dir / METRICS_FILE, default=None) or {})}
        existing["status"] = "failed"
        existing["error"] = f"{type(exc).__name__}: {exc}"
        existing["checkpoint"] = None
        write_json(project_dir / METRICS_FILE, existing)
        return 1


if __name__ == "__main__":
    code = main(cli_argv())
    if code:
        sys.exit(code)
