"""Apply the cleaning steps you approved. Generated by mlagent; safe to edit.

Run it from the project folder:

    python clean.py

Reads the raw CSV named in `data_meta.json`, applies `STEPS` in order, and writes
`data/clean/data.csv`, `profile_clean.json` (a before/after summary) and
`plots/clean_before_after_missing.png`. Every operation is a plain pandas function you
can read and change; editing `STEPS` and rerunning is the supported way to redo the
cleaning differently.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pandas.api import types as ptypes

# --- settings ---
SCRIPT_NAME = "clean.py"
PROJECT_DIR = Path(".")
META_FILE = "data_meta.json"
CLEAN_PATH = Path("data") / "clean" / "data.csv"
PROFILE_FILE = "profile_clean.json"
FIGURE_NAME = "clean_before_after_missing"
MAX_PLOTTED_COLS = 60

# --- the steps mlagent recorded ---
# Each step is {"op": name, "params": {...}} and runs in order. Edit and rerun freely.
STEPS_JSON = r"""[]"""
STEPS: list[dict] = json.loads(STEPS_JSON)

# --- captions ---
# Byte-identical to the matching entry in mlagent/captions.py (tests/test_template_clean.py
# checks this); kept here too since this script never depends on the mlagent package.
CAPTIONS = {
    "clean_before_after_missing": (
        "The percentage of missing values per column before and after cleaning. Bars that "
        "shrink to zero were filled or dropped; bars that did not move were left alone on "
        "purpose."
    ),
}

# --- palette ---
SERIES = ["#2a78d6", "#eb6834", "#1baf7a", "#eda100", "#e87ba4", "#008300", "#4a3aa7", "#e34948"]
INK, INK_2, MUTED, GRID, AXIS, SURFACE = (
    "#0b0b0b", "#52514e", "#898781", "#e1e0d9", "#c3c2b7", "#fcfcfb",
)


# --- cleaning operations ---
def drop_columns(df: pd.DataFrame, columns: list[str]) -> pd.DataFrame:
    return df.drop(columns=[c for c in columns if c in df.columns])


def drop_duplicates(df: pd.DataFrame) -> pd.DataFrame:
    return df.drop_duplicates().reset_index(drop=True)


def fill_missing(df: pd.DataFrame, column: str, strategy: str = "median",
                 value=None) -> pd.DataFrame:
    if column not in df.columns:
        return df
    s = df[column]
    if strategy == "median":
        fill = s.median()
    elif strategy == "mode":
        mode = s.mode(dropna=True)
        fill = mode.iloc[0] if not mode.empty else value
    elif strategy == "constant":
        fill = value
    else:
        raise ValueError(f"unknown fill strategy {strategy!r}")
    if fill is None:
        return df
    out = df.copy()
    out[column] = s.fillna(fill)
    return out


def drop_rows_missing_target(df: pd.DataFrame, target: str) -> pd.DataFrame:
    return df.dropna(subset=[target]).reset_index(drop=True)


def normalise_categories(df: pd.DataFrame, column: str) -> pd.DataFrame:
    if column not in df.columns:
        return df
    s = df[column]
    if not (s.dtype == "object" or s.dtype.name == "string"):
        return df
    out = df.copy()
    s = out[column]
    out[column] = s.where(s.isna(), s.astype(str).str.strip().str.lower())
    return out


def clip_outliers(df: pd.DataFrame, column: str, lower: float, upper: float) -> pd.DataFrame:
    if column not in df.columns:
        return df
    out = df.copy()
    out[column] = out[column].clip(lower=lower, upper=upper)
    return out


def coerce_numeric(df: pd.DataFrame, column: str) -> pd.DataFrame:
    if column not in df.columns:
        return df
    out = df.copy()
    out[column] = pd.to_numeric(out[column], errors="coerce")
    return out


OPS = {
    "drop_columns": drop_columns,
    "drop_duplicates": drop_duplicates,
    "fill_missing": fill_missing,
    "drop_rows_missing_target": drop_rows_missing_target,
    "normalise_categories": normalise_categories,
    "clip_outliers": clip_outliers,
    "coerce_numeric": coerce_numeric,
}


def clean(df: pd.DataFrame, steps: list[dict] | None = None) -> pd.DataFrame:
    """Run every step in order and return a new frame; the input is never modified."""
    steps = STEPS if steps is None else steps
    if not steps:
        return df.copy()
    out = df
    for step in steps:
        op = step.get("op")
        if op not in OPS:
            raise ValueError(f"unknown cleaning op {op!r}")
        out = OPS[op](out, **step.get("params", {}))
    return out


def cast_classification_target(df: pd.DataFrame, target: str) -> pd.DataFrame:
    """Whole-number float labels (a side effect of NaNs) become ints, so a label reads
    as `1`, not `1.0`."""
    if target not in df.columns:
        return df
    s = df[target]
    if not ptypes.is_float_dtype(s) or s.isna().any():
        return df
    non_null = s.dropna()
    if non_null.empty or not (non_null % 1 == 0).all():
        return df
    out = df.copy()
    out[target] = s.astype("int64")
    return out


# --- before and after summary ---
def summarise(df: pd.DataFrame) -> dict:
    return {
        "n_rows": int(len(df)),
        "n_cols": int(df.shape[1]),
        "duplicate_rows": int(df.duplicated().sum()),
        "columns": [
            {
                "name": str(c),
                "dtype": str(df[c].dtype),
                "missing": int(df[c].isna().sum()),
                "missing_pct": round(float(df[c].isna().mean() * 100), 2),
                "n_unique": int(df[c].nunique(dropna=True)),
            }
            for c in df.columns
        ],
    }


# --- figure ---
def before_after_missing(before: dict, after: dict):
    all_names = [c["name"] for c in before["columns"]]
    names = all_names[:MAX_PLOTTED_COLS]
    before_pct = {c["name"]: c["missing_pct"] for c in before["columns"]}
    after_pct = {c["name"]: c["missing_pct"] for c in after["columns"]}
    b = [before_pct[n] for n in names]
    a = [after_pct.get(n, 0.0) for n in names]
    y = np.arange(len(names))
    fig = plt.figure(figsize=(6, 0.35 * max(3, len(names)) + 1.4), facecolor=SURFACE)
    ax = fig.add_subplot(111)
    ax.barh(y - 0.18, b, height=0.34, color=SERIES[0], label="before cleaning")
    ax.barh(y + 0.18, a, height=0.34, color=SERIES[1], label="after cleaning")
    ax.set_yticks(y)
    ax.set_yticklabels(names, fontsize=8, color=INK_2)
    ax.set_xlabel("% missing", color=MUTED, fontsize=8)
    ax.invert_yaxis()
    ax.set_facecolor(SURFACE)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    for side in ("left", "bottom"):
        ax.spines[side].set_color(AXIS)
    ax.tick_params(colors=MUTED, labelsize=8)
    ax.xaxis.grid(True, color=GRID, linewidth=0.8)
    ax.set_axisbelow(True)
    title = "Missing values before and after cleaning"
    if len(names) < len(all_names):
        title += f" - showing {len(names)} of {len(all_names)} columns"
    ax.set_title(title, color=INK, fontsize=10, loc="left")
    ax.legend(frameon=False, fontsize=8, labelcolor=INK_2)
    fig.tight_layout()
    return fig


def show(fig, kind: str) -> None:
    """Display in a notebook if one is running, then print how to read the figure."""
    try:
        from IPython import get_ipython
        from IPython.display import display
    except ImportError:
        pass
    else:
        if get_ipython() is not None:
            display(fig)
    caption = CAPTIONS.get(kind, "")
    if caption:
        print("How to read this: " + caption.replace("[[", "").replace("]]", ""))


def save(fig, plots_dir: Path, name: str, kind: str) -> str:
    plots_dir.mkdir(parents=True, exist_ok=True)
    fig.savefig(plots_dir / f"{name}.png", dpi=110, bbox_inches="tight", facecolor=SURFACE)
    show(fig, kind)
    plt.close(fig)
    return f"{name}.png"


# --- command line ---
def cli_argv() -> list[str]:
    """Arguments when run as a script or via `%run`; nothing under a bare kernel cell.

    A Jupyter/Colab kernel sets `sys.argv[0]` to its own launcher (e.g.
    `ipykernel_launcher.py` or Colab's `colab_kernel_launcher.py`), which also ends in
    `.py`, so checking the extension alone would treat the kernel's own
    `-f <connection-file>.json` flags as ours and crash `argparse`. `%run script.py --flag`
    is different: there argv[0] is this script's own name, not the launcher, so its flags
    are still parsed.
    """
    name = Path(sys.argv[0]).name.lower() if sys.argv else ""
    return sys.argv[1:] if name == SCRIPT_NAME.lower() else []


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Apply the approved cleaning steps.")
    parser.add_argument("--project", default=str(PROJECT_DIR))
    args = parser.parse_args(argv)
    project_dir = Path(args.project).resolve()

    meta_path = project_dir / META_FILE
    meta = json.loads(meta_path.read_text(encoding="utf-8")) if meta_path.exists() else {}
    raw_path = project_dir / str(meta.get("raw_path") or "data/raw/data.csv")
    raw = pd.read_csv(raw_path)

    cleaned = clean(raw).reset_index(drop=True)
    target = meta.get("target")
    if target and meta.get("task_type") == "tabular_classification":
        cleaned = cast_classification_target(cleaned, str(target))

    out_path = project_dir / CLEAN_PATH
    out_path.parent.mkdir(parents=True, exist_ok=True)
    cleaned.to_csv(out_path, index=False)

    before, after = summarise(raw), summarise(cleaned)
    figures = [
        save(before_after_missing(before, after), project_dir / "plots", FIGURE_NAME,
             "clean_before_after_missing")
    ]
    (project_dir / PROFILE_FILE).write_text(
        json.dumps(
            {"before": before, "after": after, "steps": STEPS, "figures": figures},
            indent=2, sort_keys=True,
        ),
        encoding="utf-8",
    )
    print(
        f"cleaned {raw_path.name}: {before['n_rows']} x {before['n_cols']} -> "
        f"{after['n_rows']} x {after['n_cols']} rows x columns "
        f"after {len(STEPS)} step(s) -> {CLEAN_PATH.as_posix()}",
        flush=True,
    )
    return 0


if __name__ == "__main__":
    code = main(cli_argv())
    if code:
        sys.exit(code)
