"""Profile a dataset and draw its four overview figures. Generated by mlagent; safe to edit.

Run it from the project folder:

    python profile.py                                     profile the raw data
    python profile.py --input data/clean/data.csv --tag clean

Writes `profile_{tag}.json` and PNGs into `plots/`. Imports only pandas and matplotlib,
so you can run it anywhere the project folder exists.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
from matplotlib.colors import LinearSegmentedColormap
from pandas.api import types as ptypes

# --- settings ---
SCRIPT_NAME = "profile.py"
PROJECT_DIR = Path(".")
META_FILE = "data_meta.json"
TAG = "raw"
INPUT = None  # None means "the raw CSV named in data_meta.json"
MAX_HIST_COLS = 12
MAX_MISSING_ROWS = 500
MAX_MISSING_COLS = 60
MAX_CORR_COLS = 20
CATEGORICAL_MAX_UNIQUE = 50
MAX_LISTED_CATEGORIES = 20

# --- palette ---
SERIES = ["#2a78d6", "#eb6834", "#1baf7a", "#eda100", "#e87ba4", "#008300", "#4a3aa7", "#e34948"]
SEQUENTIAL = ["#cde2fb", "#9ec5f4", "#6da7ec", "#3987e5", "#256abf", "#184f95", "#0d366b"]
DIVERGING = ["#1c5cab", "#86b6ef", "#f0efec", "#f3a17f", "#d95926"]
INK, INK_2, MUTED, GRID, AXIS, SURFACE = (
    "#0b0b0b", "#52514e", "#898781", "#e1e0d9", "#c3c2b7", "#fcfcfb",
)
SEQ_CMAP = LinearSegmentedColormap.from_list("mlagent_seq", SEQUENTIAL)
DIV_CMAP = LinearSegmentedColormap.from_list("mlagent_div", DIVERGING)


def style(ax, title=None, grid_axis="y"):
    ax.set_facecolor(SURFACE)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    for side in ("left", "bottom"):
        ax.spines[side].set_color(AXIS)
    ax.tick_params(colors=MUTED, labelsize=8)
    ax.grid(False)
    if grid_axis in ("y", "both"):
        ax.yaxis.grid(True, color=GRID, linewidth=0.8)
    if grid_axis in ("x", "both"):
        ax.xaxis.grid(True, color=GRID, linewidth=0.8)
    ax.set_axisbelow(True)
    if title:
        ax.set_title(title, color=INK, fontsize=10, loc="left")


# --- reading the data ---
def read_json(path: Path, default=None):
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def load_frame(project_dir: Path, input_path: str | None, meta: dict):
    relative = input_path or meta.get("raw_path") or "data/raw/data.csv"
    path = project_dir / relative
    if not path.exists():
        raise FileNotFoundError(f"no data file at {path}")
    return pd.read_csv(path), path


# --- describing the columns ---
def to_python(value):
    """numpy scalars become plain Python; NaN becomes None so the JSON is valid."""
    if value is None or value is pd.NA:
        return None
    if isinstance(value, float) and pd.isna(value):
        return None
    if hasattr(value, "item"):
        value = value.item()
    if isinstance(value, float) and math.isnan(value):
        return None
    return value


def is_categorical(s: pd.Series) -> bool:
    if ptypes.is_bool_dtype(s) or not ptypes.is_numeric_dtype(s):
        return True
    vals = s.dropna()
    if vals.empty or vals.nunique() > CATEGORICAL_MAX_UNIQUE:
        return False
    return bool((vals % 1 == 0).all())


def column_info(name: str, s: pd.Series) -> dict:
    info = {
        "name": name,
        "dtype": str(s.dtype),
        "missing": int(s.isna().sum()),
        "missing_pct": round(float(s.isna().mean() * 100), 2),
        "n_unique": int(s.nunique(dropna=True)),
        "sample": [str(v) for v in s.dropna().unique()[:5]],
    }
    if ptypes.is_numeric_dtype(s) and not ptypes.is_bool_dtype(s):
        vals = s.dropna()
        if not vals.empty:
            info.update({
                "min": to_python(vals.min()),
                "max": to_python(vals.max()),
                "mean": to_python(round(float(vals.mean()), 6)),
                "std": to_python(round(float(vals.std()), 6)) if len(vals) > 1 else 0.0,
            })
    return info


def target_info(name: str, s: pd.Series) -> dict:
    if is_categorical(s):
        all_counts = s.value_counts(dropna=True)
        counts = all_counts.head(MAX_LISTED_CATEGORIES)
        return {
            "name": name,
            "kind": "categorical",
            "n_classes": int(all_counts.shape[0]),
            "total": int(all_counts.sum()),
            "counts": {str(k): int(v) for k, v in counts.items()},
        }
    vals = s.dropna()
    if vals.empty:
        return {"name": name, "kind": "numeric", "min": None, "max": None, "mean": None,
                "std": None}
    return {
        "name": name,
        "kind": "numeric",
        "min": to_python(vals.min()),
        "max": to_python(vals.max()),
        "mean": to_python(round(float(vals.mean()), 6)),
        "std": to_python(round(float(vals.std()), 6)) if len(vals) > 1 else 0.0,
    }


def profile_frame(df: pd.DataFrame, target: str | None) -> dict:
    profile = {
        "n_rows": int(len(df)),
        "n_cols": int(df.shape[1]),
        "duplicate_rows": int(df.duplicated().sum()),
        "memory_mb": round(float(df.memory_usage(deep=True).sum() / 1e6), 3),
        "columns": [column_info(str(c), df[c]) for c in df.columns],
        "target": None,
    }
    if target is not None and target in df.columns:
        profile["target"] = target_info(target, df[target])
    return profile


# --- figures ---
def numeric_columns(df: pd.DataFrame) -> list[str]:
    return [
        c for c in df.columns
        if ptypes.is_numeric_dtype(df[c]) and not ptypes.is_bool_dtype(df[c])
    ]


def show(fig) -> None:
    """Display in a notebook if one is running; do nothing from a plain shell."""
    try:
        from IPython import get_ipython
        from IPython.display import display
    except ImportError:
        return
    if get_ipython() is not None:
        display(fig)


def save(fig, plots_dir: Path, name: str) -> str:
    plots_dir.mkdir(parents=True, exist_ok=True)
    fig.savefig(plots_dir / f"{name}.png", dpi=110, bbox_inches="tight", facecolor=SURFACE)
    show(fig)
    plt.close(fig)
    return f"{name}.png"


def histograms(df: pd.DataFrame):
    cols = numeric_columns(df)[:MAX_HIST_COLS]
    n = max(1, len(cols))
    ncols = min(4, n)
    nrows = math.ceil(n / ncols)
    fig, axes = plt.subplots(nrows, ncols, figsize=(3.2 * ncols, 2.4 * nrows),
                             facecolor=SURFACE, squeeze=False)
    for ax, col in zip(axes.flat, cols, strict=False):
        ax.hist(df[col].dropna(), bins=30, color=SERIES[0], edgecolor=SURFACE, linewidth=0.5)
        style(ax, col)
    for ax in list(axes.flat)[len(cols):]:
        ax.set_visible(False)
    if not cols:
        axes[0][0].set_visible(True)
        axes[0][0].text(0.5, 0.5, "no numeric columns", ha="center", color=MUTED)
    fig.suptitle("Feature distributions", color=INK, fontsize=11, x=0.01, ha="left")
    fig.tight_layout()
    return fig


def missing_matrix(df: pd.DataFrame):
    sample = df if len(df) <= MAX_MISSING_ROWS else df.sample(
        MAX_MISSING_ROWS, random_state=0
    ).sort_index()
    columns = list(df.columns)[:MAX_MISSING_COLS]
    mat = sample[columns].isna().to_numpy().T.astype(float)
    fig = plt.figure(figsize=(7, 0.28 * len(columns) + 1.5), facecolor=SURFACE)
    ax = fig.add_subplot(111)
    ax.imshow(mat, aspect="auto", cmap=SEQ_CMAP, interpolation="nearest", vmin=0, vmax=1)
    ax.set_yticks(range(len(columns)))
    ax.set_yticklabels([str(c) for c in columns], fontsize=8, color=INK_2)
    ax.set_xlabel(f"rows (showing {len(sample)} of {len(df)})", color=MUTED, fontsize=8)
    style(ax, "Missing values (dark = missing)", grid_axis="none")
    fig.tight_layout()
    return fig


def class_balance(counts: dict, total: int | None):
    fig = plt.figure(figsize=(5, 0.5 * max(3, len(counts)) + 1.2), facecolor=SURFACE)
    ax = fig.add_subplot(111)
    labels = [str(k) for k in counts]
    values = [int(v) for v in counts.values()]
    denom = total if total else (sum(values) or 1)
    ax.barh(labels, values, color=SERIES[0], height=0.6)
    for i, v in enumerate(values):
        ax.text(v, i, f"  {v} ({v / denom:.0%})", va="center", color=INK_2, fontsize=8)
    style(ax, "Target class balance", grid_axis="x")
    ax.invert_yaxis()
    ax.set_xlim(0, max(values) * 1.3 if values else 1)
    fig.tight_layout()
    return fig


def target_distribution(series: pd.Series):
    fig = plt.figure(figsize=(5, 2.8), facecolor=SURFACE)
    ax = fig.add_subplot(111)
    ax.hist(series.dropna(), bins=40, color=SERIES[0], edgecolor=SURFACE, linewidth=0.5)
    style(ax, "Target distribution")
    fig.tight_layout()
    return fig


def correlation_heatmap(df: pd.DataFrame):
    numeric = df[numeric_columns(df)[:MAX_CORR_COLS]]
    fig = plt.figure(figsize=(6, 5), facecolor=SURFACE)
    ax = fig.add_subplot(111)
    corr = numeric.corr().to_numpy()
    im = ax.imshow(corr, cmap=DIV_CMAP, vmin=-1, vmax=1)
    ticks = range(numeric.shape[1])
    ax.set_xticks(ticks)
    ax.set_yticks(ticks)
    ax.set_xticklabels(numeric.columns, rotation=60, ha="right", fontsize=8, color=INK_2)
    ax.set_yticklabels(numeric.columns, fontsize=8, color=INK_2)
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04).ax.tick_params(colors=MUTED, labelsize=8)
    style(ax, "Correlation between numeric columns", grid_axis="none")
    fig.tight_layout()
    return fig


def draw_all(df: pd.DataFrame, profile: dict, plots_dir: Path, tag: str) -> list[str]:
    figures = [
        save(histograms(df), plots_dir, f"{tag}_histograms"),
        save(missing_matrix(df), plots_dir, f"{tag}_missing"),
    ]
    target = profile.get("target")
    if target and target["kind"] == "categorical":
        figures.append(
            save(class_balance(target["counts"], target.get("total")), plots_dir,
                 f"{tag}_class_balance")
        )
    elif target:
        figures.append(
            save(target_distribution(df[target["name"]]), plots_dir,
                 f"{tag}_target_distribution")
        )
    if len(numeric_columns(df)) >= 2:
        figures.append(save(correlation_heatmap(df), plots_dir, f"{tag}_correlation"))
    return figures


# --- command line ---
def cli_argv() -> list[str]:
    """Arguments when run as a script or via `%run`; nothing under a bare kernel cell.

    A Jupyter/Colab kernel sets `sys.argv[0]` to its own launcher (e.g.
    `ipykernel_launcher.py` or Colab's `colab_kernel_launcher.py`), which also ends in
    `.py`, so checking the extension alone would treat the kernel's own
    `-f <connection-file>.json` flags as ours and crash `argparse`. `%run script.py --flag`
    is different: there argv[0] is this script's own name, not the launcher, so its flags
    are still parsed.
    """
    name = Path(sys.argv[0]).name.lower() if sys.argv else ""
    return sys.argv[1:] if name == SCRIPT_NAME.lower() else []


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Profile a dataset and draw its figures.")
    parser.add_argument("--project", default=str(PROJECT_DIR))
    parser.add_argument("--input", default=INPUT, help="CSV path relative to --project")
    parser.add_argument("--tag", default=TAG, help="prefix for the output files")
    args = parser.parse_args(argv)

    project_dir = Path(args.project).resolve()
    meta = read_json(project_dir / META_FILE, default={}) or {}
    df, path = load_frame(project_dir, args.input, meta)
    profile = profile_frame(df, meta.get("target"))
    profile["figures"] = draw_all(df, profile, project_dir / "plots", args.tag)
    out = project_dir / f"profile_{args.tag}.json"
    out.write_text(json.dumps(profile, indent=2, sort_keys=True), encoding="utf-8")
    print(
        f"profiled {path.name}: {profile['n_rows']} rows x {profile['n_cols']} columns "
        f"-> {out.name} and {len(profile['figures'])} figures",
        flush=True,
    )
    return 0


if __name__ == "__main__":
    code = main(cli_argv())
    if code:
        sys.exit(code)
