"""Load the cleaned dataset and split it. Generated by mlagent; safe to edit.

Reads data_meta.json (target, task type, feature and categorical columns, split
fractions) and data/clean/data.csv. Categorical columns are ordinal-encoded using
the categories seen in the training split; unseen values become NaN, which
HistGradientBoosting handles natively.

The train/val/test split is seeded from data_meta.json's `split_seed` (default 42),
never from config.json, so the held-out test split is the same for every run and a
checkpoint's validation numbers stay comparable across tuning. config.json's `seed`
only seeds the model (see model.py).
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

META_FILE = "data_meta.json"
MAX_CATEGORY_CODES = 200  # above this a column is treated as plain numeric codes


def read_meta(project_dir: Path) -> dict:
    return json.loads((project_dir / META_FILE).read_text(encoding="utf-8"))


def _encode_column(series: pd.Series, categories: list[str]) -> pd.Series:
    mapping = {value: float(i) for i, value in enumerate(categories)}
    values = [mapping.get(str(v), np.nan) if pd.notna(v) else np.nan for v in series.tolist()]
    return pd.Series(values, index=series.index, dtype=float)


def encode_features(
    df: pd.DataFrame,
    categorical_columns: list[str],
    categories: dict[str, list[str]] | None = None,
) -> tuple[pd.DataFrame, dict[str, list[str]], list[bool]]:
    """Return (encoded frame, categories per column, categorical mask per column).

    Pass the `categories` returned for the training split when encoding validation
    and test splits so codes line up.
    """
    out = df.copy()
    cats: dict[str, list[str]] = dict(categories or {})
    for col in out.columns:
        if col in categorical_columns:
            if col not in cats:
                cats[col] = sorted(out[col].dropna().astype(str).unique().tolist())
            out[col] = _encode_column(out[col], cats[col])
        else:
            out[col] = pd.to_numeric(out[col], errors="coerce").astype(float)
    mask = [
        col in categorical_columns and len(cats.get(col, [])) <= MAX_CATEGORY_CODES
        for col in out.columns
    ]
    return out, cats, mask


def _split(X: pd.DataFrame, y: pd.Series, fraction: float, seed: int, stratify: bool):
    strat = y if stratify and y.value_counts().min() >= 2 else None
    try:
        return train_test_split(X, y, test_size=fraction, random_state=seed, stratify=strat)
    except ValueError:
        return train_test_split(X, y, test_size=fraction, random_state=seed)


def load_data(project_dir: Path | str, config: dict) -> dict:
    project_dir = Path(project_dir)
    meta = read_meta(project_dir)
    df = pd.read_csv(project_dir / meta["clean_path"])
    target = meta["target"]
    if target not in df.columns:
        raise ValueError(f"target column {target!r} not in {meta['clean_path']}")
    df = df[df[target].notna()].reset_index(drop=True)
    wanted = meta.get("feature_columns") or [c for c in df.columns if c != target]
    features = [c for c in wanted if c in df.columns and c != target]
    if not features:
        raise ValueError("no feature columns available")
    categorical = [c for c in meta.get("categorical_columns", []) if c in features]
    task_type = meta["task_type"]

    X = df[features]
    y = df[target]
    classes: list[str] | None = None
    if task_type == "tabular_classification":
        classes = [str(c) for c in (meta.get("class_labels") or sorted(y.astype(str).unique()))]
        index = {label: i for i, label in enumerate(classes)}
        y = y.astype(str).map(index)
        if y.isna().any():
            raise ValueError("target has labels outside class_labels in data_meta.json")
        y = y.astype(int)
    else:
        y = pd.to_numeric(y, errors="raise").astype(float)

    splits = meta["splits"]
    seed = int(meta.get("split_seed", 42))
    test_frac = float(splits["test"])
    val_frac = float(splits["val"]) / max(1e-9, 1.0 - test_frac)
    X_tv, X_test, y_tv, y_test = _split(X, y, test_frac, seed, classes is not None)
    X_train, X_val, y_train, y_val = _split(X_tv, y_tv, val_frac, seed, classes is not None)

    X_train_e, cats, mask = encode_features(X_train, categorical)
    X_val_e, _, _ = encode_features(X_val, categorical, cats)
    X_test_e, _, _ = encode_features(X_test, categorical, cats)

    data = {
        "X_train": X_train_e,
        "y_train": y_train.to_numpy(),
        "X_val": X_val_e,
        "y_val": y_val.to_numpy(),
        "X_test": X_test_e,
        "y_test": y_test.to_numpy(),
        "feature_names": features,
        "categorical_mask": mask,
        "classes": classes,
        "task_type": task_type,
    }
    validate(data)
    return data


def validate(data: dict) -> None:
    """Raise ValueError if the splits are unusable: empty, overlapping, or one class."""
    for name in ("X_train", "X_val", "X_test"):
        if len(data[name]) == 0:
            raise ValueError(f"{name} is empty; adjust the split fractions")
    idx = {name: set(data[name].index) for name in ("X_train", "X_val", "X_test")}
    if (idx["X_train"] & idx["X_val"]) or (idx["X_train"] & idx["X_test"]) or (
        idx["X_val"] & idx["X_test"]
    ):
        raise ValueError("splits overlap: the same row appears in two splits")
    if data.get("classes") is not None and len(np.unique(data["y_train"])) < 2:
        raise ValueError("training split contains fewer than 2 classes")
