"""Build the model. Generated by mlagent; safe to edit.

One wrapper, `EpochModel`, gives all three families the same shape so `train.py` can add
capacity one epoch at a time and record a real learning curve:

- gradient_boosting: HistGradientBoosting with warm_start; an epoch adds `iters_per_epoch`
  boosting rounds to the same ensemble.
- random_forest: RandomForest with warm_start; an epoch adds `trees_per_epoch` trees.
- linear: SGDClassifier/SGDRegressor; an epoch is one `partial_fit` pass over the training
  rows. Linear models cannot cope with missing values or wildly different scales, so this
  family fills gaps with each column's median and standardises before fitting.
"""

from __future__ import annotations

import numpy as np
from sklearn.ensemble import (
    HistGradientBoostingClassifier,
    HistGradientBoostingRegressor,
    RandomForestClassifier,
    RandomForestRegressor,
)
from sklearn.impute import SimpleImputer
from sklearn.linear_model import SGDClassifier, SGDRegressor
from sklearn.preprocessing import StandardScaler

# --- settings ---
MODEL_TYPES = ("gradient_boosting", "random_forest", "linear")
CLASSIFICATION = "tabular_classification"
REGRESSION = "tabular_regression"


# --- one epoch at a time ---
class EpochModel:
    """A scikit-learn estimator plus the rule for what 'one more epoch' means."""

    def __init__(self, estimator, model_type: str, task_type: str, step: int = 0):
        self.estimator = estimator
        self.model_type = model_type
        self.task_type = task_type
        self.step = int(step)
        self.epochs_fitted = 0
        self.imputer = SimpleImputer(strategy="median")
        self.scaler = StandardScaler()

    # Linear models need numbers with no gaps and comparable scales.
    def _prepare(self, X, fit: bool = False):
        if fit:
            return self.scaler.fit_transform(self.imputer.fit_transform(X))
        return self.scaler.transform(self.imputer.transform(X))

    def fit_epoch(self, X, y) -> EpochModel:
        first = self.epochs_fitted == 0
        if self.model_type == "gradient_boosting":
            if not first:
                self.estimator.set_params(max_iter=int(self.estimator.max_iter) + self.step)
            self.estimator.fit(X, y)
        elif self.model_type == "random_forest":
            if not first:
                self.estimator.set_params(
                    n_estimators=int(self.estimator.n_estimators) + self.step
                )
            self.estimator.fit(X, y)
        else:
            Xs = self._prepare(X, fit=first)
            if self.task_type == CLASSIFICATION and first:
                self.estimator.partial_fit(Xs, y, classes=np.unique(np.asarray(y)))
            else:
                self.estimator.partial_fit(Xs, y)
        self.epochs_fitted += 1
        return self

    def _features(self, X):
        return self._prepare(X) if self.model_type == "linear" else X

    def predict(self, X):
        return self.estimator.predict(self._features(X))

    def predict_proba(self, X):
        return self.estimator.predict_proba(self._features(X))

    @property
    def classes_(self):
        return getattr(self.estimator, "classes_", None)


# --- building each family ---
def _gradient_boosting(config: dict, task_type: str, categorical_mask: list[bool]):
    params = {
        "learning_rate": float(config.get("learning_rate", 0.1)),
        "max_iter": int(config.get("iters_per_epoch", 10)),
        "max_leaf_nodes": int(config.get("max_leaf_nodes", 31)),
        "max_depth": config.get("max_depth"),
        "min_samples_leaf": int(config.get("min_samples_leaf", 20)),
        "l2_regularization": float(config.get("l2_regularization", 0.0)),
        "categorical_features": list(categorical_mask) if any(categorical_mask) else None,
        "warm_start": True,
        "early_stopping": False,
        "random_state": int(config.get("seed", 42)),
    }
    cls = HistGradientBoostingClassifier if task_type == CLASSIFICATION \
        else HistGradientBoostingRegressor
    return cls(**params), int(config.get("iters_per_epoch", 10))


def _random_forest(config: dict, task_type: str, _categorical_mask: list[bool]):
    trees = int(config.get("trees_per_epoch", 20))
    params = {
        "n_estimators": trees,
        "max_depth": config.get("max_depth"),
        "min_samples_leaf": int(config.get("min_samples_leaf", 1)),
        "max_features": float(config.get("max_features", 1.0)),
        "warm_start": True,
        "random_state": int(config.get("seed", 42)),
    }
    cls = RandomForestClassifier if task_type == CLASSIFICATION else RandomForestRegressor
    return cls(**params), trees


def _linear(config: dict, task_type: str, _categorical_mask: list[bool]):
    rate = float(config.get("learning_rate", 0.01))
    alpha = float(config.get("alpha", 0.0001))
    seed = int(config.get("seed", 42))
    if task_type == CLASSIFICATION:
        estimator = SGDClassifier(
            loss="log_loss", alpha=alpha, learning_rate="constant", eta0=rate,
            random_state=seed,
        )
    else:
        estimator = SGDRegressor(
            alpha=alpha, learning_rate="constant", eta0=rate, random_state=seed
        )
    return estimator, 1


BUILDERS = {
    "gradient_boosting": _gradient_boosting,
    "random_forest": _random_forest,
    "linear": _linear,
}


def build_model(config: dict, task_type: str, categorical_mask: list[bool]) -> EpochModel:
    model_type = str(config.get("model_type", "gradient_boosting"))
    if model_type not in BUILDERS:
        raise ValueError(f"unknown model_type {model_type!r}; expected one of {MODEL_TYPES}")
    if task_type not in (CLASSIFICATION, REGRESSION):
        raise ValueError(f"unsupported task_type {task_type!r} for the tabular_sklearn template")
    estimator, step = BUILDERS[model_type](config, task_type, list(categorical_mask))
    return EpochModel(estimator, model_type, task_type, step)
