"""Build the model. Generated by mlagent; safe to edit.

HistGradientBoosting with warm_start=True: each "epoch" in train.py adds
`iters_per_epoch` boosting rounds, so train/validation loss can be tracked per epoch.
"""

from __future__ import annotations

from sklearn.ensemble import HistGradientBoostingClassifier, HistGradientBoostingRegressor


def build_model(config: dict, task_type: str, categorical_mask: list[bool]):
    params = {
        "learning_rate": float(config.get("learning_rate", 0.1)),
        "max_iter": int(config.get("iters_per_epoch", 10)),
        "max_leaf_nodes": int(config.get("max_leaf_nodes", 31)),
        "max_depth": config.get("max_depth"),
        "min_samples_leaf": int(config.get("min_samples_leaf", 20)),
        "l2_regularization": float(config.get("l2_regularization", 0.0)),
        "categorical_features": list(categorical_mask) if any(categorical_mask) else None,
        "warm_start": True,
        "early_stopping": False,
        "random_state": int(config.get("seed", 42)),
    }
    if task_type == "tabular_classification":
        return HistGradientBoostingClassifier(**params)
    if task_type == "tabular_regression":
        return HistGradientBoostingRegressor(**params)
    raise ValueError(f"unsupported task_type {task_type!r} for the tabular_sklearn template")


def grow(model, iters: int):
    """Add `iters` boosting rounds on the next fit() call (warm start keeps earlier rounds)."""
    model.set_params(max_iter=int(model.max_iter) + int(iters))
    return model
