"""Train, evaluate per epoch, write metrics.json. Generated by mlagent; safe to edit.

Usage (run from the project folder):
  python train.py                            full training run
  python train.py --dry-run                  one boosting round; prints timing and n_train
  python train.py --eval-test                evaluate checkpoints/best.joblib on the test split
  python train.py --eval-test --checkpoint P  evaluate a specific checkpoint (relative path)
"""

from __future__ import annotations

import argparse
import copy
import json
import math
import os
import sys
import tempfile
import time
import traceback
from pathlib import Path

import joblib
import numpy as np
from data import load_data
from model import build_model
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    log_loss,
    mean_absolute_error,
    mean_squared_error,
    r2_score,
)

CONFIG_FILE = "config.json"
SPEC_FILE = "spec.json"
METRICS_FILE = "metrics.json"
EVAL_VAL_FILE = "eval_val.json"
EVAL_TEST_FILE = "eval_test.json"
CHECKPOINT = Path("checkpoints") / "best.joblib"
HIGHER_IS_BETTER = {"accuracy": True, "f1": True, "r2": True, "rmse": False, "mae": False}
DEFAULT_METRIC = {"tabular_classification": "accuracy", "tabular_regression": "rmse"}
EPS = 1e-12


def read_json(path: Path, default=None):
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, obj) -> None:
    """Atomic write so a reader polling the file never sees a partial JSON document."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.", suffix=".tmp")
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(json.dumps(obj, indent=2, sort_keys=True))
    # Windows: os.replace can fail with PermissionError if a poller has the target open; retry.
    attempts = 20
    for attempt in range(attempts):
        try:
            os.replace(tmp, path)
            return
        except PermissionError:
            if attempt == attempts - 1:
                Path(tmp).unlink(missing_ok=True)
                raise
            time.sleep(0.05)


def compute_metric(name: str, y_true, y_pred) -> float:
    if name == "accuracy":
        return float(accuracy_score(y_true, y_pred))
    if name == "f1":
        return float(f1_score(y_true, y_pred, average="macro"))
    if name == "rmse":
        return float(math.sqrt(mean_squared_error(y_true, y_pred)))
    if name == "mae":
        return float(mean_absolute_error(y_true, y_pred))
    if name == "r2":
        return float(r2_score(y_true, y_pred))
    raise ValueError(f"unknown metric {name!r}")


def full_proba(model, X, n_classes: int) -> np.ndarray:
    """predict_proba with one column per class even if a class was absent from training."""
    proba = model.predict_proba(X)
    out = np.zeros((len(X), n_classes), dtype=float)
    out[:, np.asarray(model.classes_, dtype=int)] = proba
    out = np.clip(out, EPS, None)
    out /= out.sum(axis=1, keepdims=True)
    return out


def evaluate(model, X, y, task_type: str, metric: str, n_classes: int | None) -> dict:
    y_pred = model.predict(X)
    if task_type == "tabular_classification":
        proba = full_proba(model, X, n_classes)
        loss = float(log_loss(y, proba, labels=list(range(n_classes))))
        y_proba = proba.tolist()
    else:
        loss = float(mean_squared_error(y, y_pred))
        y_proba = None
    return {
        "loss": loss,
        "value": compute_metric(metric, y, y_pred),
        "y_true": np.asarray(y).tolist(),
        "y_pred": np.asarray(y_pred).tolist(),
        "y_proba": y_proba,
    }


def eval_record(split: str, task_type: str, metric: str, classes, ev: dict) -> dict:
    return {
        "split": split,
        "task_type": task_type,
        "metric": metric,
        "value": ev["value"],
        "loss": ev["loss"],
        "classes": classes,
        "y_true": ev["y_true"],
        "y_pred": ev["y_pred"],
        "y_proba": ev["y_proba"],
    }


def metric_for(project_dir: Path, task_type: str) -> str:
    spec = read_json(project_dir / SPEC_FILE, default={}) or {}
    return str(spec.get("metric") or DEFAULT_METRIC[task_type])


def empty_metrics() -> dict:
    """Return a metrics dict with all required keys and placeholder values."""
    return {
        "status": "running",
        "task_type": None,
        "metric": None,
        "higher_is_better": None,
        "config": None,
        "classes": None,
        "n_train": None,
        "n_val": None,
        "n_test": None,
        "epochs": [],
        "best_epoch": None,
        "best_val_metric": None,
        "stopped_early": False,
        "error": None,
        "seconds": None,
        "seconds_per_epoch": None,
    }


def train(project_dir: Path, dry_run: bool = False) -> dict:
    config = read_json(project_dir / CONFIG_FILE, default={}) or {}
    data = load_data(project_dir, config)
    task_type = data["task_type"]
    metric = metric_for(project_dir, task_type)
    higher = HIGHER_IS_BETTER[metric]
    n_classes = len(data["classes"]) if data["classes"] is not None else None
    epochs = int(config.get("epochs", 10))
    iters = int(config.get("iters_per_epoch", 10))
    configured_iters_per_epoch = iters
    patience = int(config.get("early_stopping_patience", 0))
    if dry_run:
        epochs, iters, patience = 1, 1, 0
    config = {**config, "iters_per_epoch": iters}
    metrics_path = None if dry_run else project_dir / METRICS_FILE

    metrics = empty_metrics()
    metrics.update({
        "task_type": task_type,
        "metric": metric,
        "higher_is_better": higher,
        "config": config,
        "classes": data["classes"],
        "n_train": int(len(data["X_train"])),
        "n_val": int(len(data["X_val"])),
        "n_test": int(len(data["X_test"])),
    })

    def save() -> None:
        if metrics_path is not None:
            write_json(metrics_path, metrics)

    save()
    model = build_model(config, task_type, data["categorical_mask"])
    best_model = None
    best_value = None
    since_best = 0
    started = time.time()
    for epoch in range(1, epochs + 1):
        t0 = time.time()
        model.fit_epoch(data["X_train"], data["y_train"])
        tr = evaluate(model, data["X_train"], data["y_train"], task_type, metric, n_classes)
        va = evaluate(model, data["X_val"], data["y_val"], task_type, metric, n_classes)
        row = {
            "epoch": epoch,
            "train_loss": tr["loss"],
            "val_loss": va["loss"],
            "train_metric": tr["value"],
            "val_metric": va["value"],
            "seconds": round(time.time() - t0, 3),
        }
        metrics["epochs"].append(row)
        if not (math.isfinite(row["train_loss"]) and math.isfinite(row["val_loss"])):
            metrics["status"] = "failed"
            metrics["error"] = f"non-finite loss at epoch {epoch}"
            save()
            return metrics
        improved = best_value is None or (
            row["val_metric"] > best_value if higher else row["val_metric"] < best_value
        )
        if improved:
            best_value = row["val_metric"]
            metrics["best_epoch"] = epoch
            metrics["best_val_metric"] = best_value
            best_model = copy.deepcopy(model)
            since_best = 0
        else:
            since_best += 1
        save()
        print(
            f"epoch {epoch}/{epochs} train_loss={row['train_loss']:.4f} "
            f"val_loss={row['val_loss']:.4f} val_{metric}={row['val_metric']:.4f}",
            flush=True,
        )
        if patience and since_best >= patience:
            metrics["stopped_early"] = True
            break

    elapsed = time.time() - started
    metrics["seconds"] = round(elapsed, 3)
    metrics["seconds_per_epoch"] = round(elapsed / max(1, len(metrics["epochs"])), 4)
    if dry_run:
        seconds_per_round = metrics["seconds_per_epoch"]
        print(json.dumps({
            "seconds_per_round": seconds_per_round,
            "seconds_per_epoch": round(seconds_per_round * configured_iters_per_epoch, 4),
            "n_train": metrics["n_train"],
        }), flush=True)
        return metrics

    (project_dir / CHECKPOINT).parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(best_model, project_dir / CHECKPOINT)
    va = evaluate(best_model, data["X_val"], data["y_val"], task_type, metric, n_classes)
    write_json(project_dir / EVAL_VAL_FILE,
               eval_record("val", task_type, metric, data["classes"], va))
    metrics["status"] = "done"
    save()
    return metrics


def eval_test(project_dir: Path, checkpoint: str | None = None) -> dict:
    checkpoint_path = project_dir / (checkpoint if checkpoint else CHECKPOINT)
    if not checkpoint_path.exists():
        raise FileNotFoundError(f"no checkpoint at {checkpoint_path}; run train.py first")
    config = read_json(project_dir / CONFIG_FILE, default={}) or {}
    data = load_data(project_dir, config)
    task_type = data["task_type"]
    metric = metric_for(project_dir, task_type)
    n_classes = len(data["classes"]) if data["classes"] is not None else None
    model = joblib.load(checkpoint_path)
    te = evaluate(model, data["X_test"], data["y_test"], task_type, metric, n_classes)
    record = eval_record("test", task_type, metric, data["classes"], te)
    write_json(project_dir / EVAL_TEST_FILE, record)
    print(f"test {metric}={te['value']:.4f} loss={te['loss']:.4f}", flush=True)
    return record


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", default=".", help="project folder (default: cwd)")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--eval-test", action="store_true")
    parser.add_argument(
        "--checkpoint", default=None,
        help="checkpoint path relative to --project (default: checkpoints/best.joblib)",
    )
    args = parser.parse_args(argv)
    project_dir = Path(args.project).resolve()
    try:
        if args.eval_test:
            eval_test(project_dir, checkpoint=args.checkpoint)
            return 0
        if not args.dry_run:
            # Fresh placeholders before training starts, so a failure before the first
            # save() cannot leave a previous run's epochs/best metric on disk.
            write_json(project_dir / METRICS_FILE, empty_metrics())
        metrics = train(project_dir, dry_run=args.dry_run)
        return 0 if metrics["status"] != "failed" else 1
    except Exception as exc:  # noqa: BLE001 - record any failure for the runner
        traceback.print_exc()
        if not args.eval_test and not args.dry_run:
            read_metrics = read_json(project_dir / METRICS_FILE, default=None) or {}
            existing = {**empty_metrics(), **read_metrics}
            existing["status"] = "failed"
            existing["error"] = f"{type(exc).__name__}: {exc}"
            write_json(project_dir / METRICS_FILE, existing)
        else:
            print(f"error: {exc}", flush=True)
        return 1


if __name__ == "__main__":
    sys.exit(main())
