"""Train, evaluate per epoch, write metrics.json. Generated by mlagent; safe to edit.

Usage (run from the project folder):
  python train.py                one full training run
  python train.py --dry-run      one round; prints timing and n_train, writes nothing

After training, run `evaluate.py` to score the saved checkpoint and draw its figures.
"""

from __future__ import annotations

import argparse
import copy
import json
import math
import os
import sys
import tempfile
import time
import traceback
from datetime import datetime, timezone
from pathlib import Path

import joblib
import matplotlib.pyplot as plt
from data import load_data
from evaluate import (
    HIGHER_IS_BETTER,
    INK_2,
    MUTED,
    SERIES,
    SURFACE,
    evaluate_split,
    frame,
    metric_for,
)
from model import build_model

# --- settings ---
SCRIPT_NAME = "train.py"
CONFIG_FILE = "config.json"
METRICS_FILE = "metrics.json"
CHECKPOINT = Path("checkpoints") / "best.joblib"
CURVES_FIGURE = Path("plots") / "training_curves.png"


# --- small helpers ---
def read_json(path: Path, default=None):
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, obj) -> None:
    """Atomic write so a reader polling the file never sees a partial JSON document."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.", suffix=".tmp")
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(json.dumps(obj, indent=2, sort_keys=True))
    # Windows: os.replace can fail with PermissionError if a poller has the target open; retry.
    attempts = 20
    for attempt in range(attempts):
        try:
            os.replace(tmp, path)
            return
        except PermissionError:
            if attempt == attempts - 1:
                Path(tmp).unlink(missing_ok=True)
                raise
            time.sleep(0.05)


def empty_metrics() -> dict:
    """Return a metrics dict with all required keys and placeholder values."""
    return {
        "status": "running",
        "started_at": None,
        "model_type": None,
        "task_type": None,
        "metric": None,
        "higher_is_better": None,
        "config": None,
        "classes": None,
        "n_train": None,
        "n_val": None,
        "n_test": None,
        "epochs": [],
        "best_epoch": None,
        "best_val_metric": None,
        "stopped_early": False,
        "error": None,
        "seconds": None,
        "seconds_per_epoch": None,
    }


# --- the live training curve ---
_HANDLE = None


def training_curves(epochs: list[dict], metric: str):
    fig, (ax_loss, ax_metric) = plt.subplots(1, 2, figsize=(9, 3.2), facecolor=SURFACE)
    xs = [e["epoch"] for e in epochs]
    panels = (
        (ax_loss, ("train_loss", "val_loss"), "Loss per epoch"),
        (ax_metric, ("train_metric", "val_metric"), f"{metric} per epoch"),
    )
    for ax, keys, title in panels:
        for key, colour, label in zip(keys, SERIES[:2], ("train", "validation"), strict=True):
            ax.plot(xs, [e.get(key) for e in epochs], color=colour, linewidth=2,
                    marker="o", markersize=4, label=label)
        frame(ax, title)
        ax.set_xlabel("epoch", color=INK_2, fontsize=8)
        ax.legend(frameon=False, fontsize=8, labelcolor=INK_2)
    if not epochs:
        ax_loss.text(0.5, 0.5, "no epochs yet", ha="center", va="center", color=MUTED,
                     transform=ax_loss.transAxes)
    fig.tight_layout()
    return fig


def redraw(fig) -> None:
    """Update one output area in place, so the curve animates instead of stacking up."""
    global _HANDLE
    try:
        from IPython import get_ipython
        from IPython.display import display
    except ImportError:
        return
    if get_ipython() is None:
        return
    if _HANDLE is None:
        _HANDLE = display(fig, display_id=True)
    else:
        _HANDLE.update(fig)


def draw_curves(project_dir: Path, epochs: list[dict], metric: str) -> None:
    fig = training_curves(epochs, metric)
    path = project_dir / CURVES_FIGURE
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=110, bbox_inches="tight", facecolor=SURFACE)
    redraw(fig)
    plt.close(fig)


# --- training ---
def dry_run_timing(project_dir: Path) -> dict:
    """Time one real fit_epoch for whichever family is configured; write nothing."""
    config = read_json(project_dir / CONFIG_FILE, default={}) or {}
    data = load_data(project_dir, config)
    model = build_model(config, data["task_type"], data["categorical_mask"])
    n_train = int(len(data["X_train"]))
    t0 = time.time()
    model.fit_epoch(data["X_train"], data["y_train"])
    seconds_per_epoch = round(time.time() - t0, 4)
    print(json.dumps({
        "seconds_per_epoch": seconds_per_epoch,
        "n_train": n_train,
    }), flush=True)
    metrics = empty_metrics()
    metrics["seconds_per_epoch"] = seconds_per_epoch
    metrics["n_train"] = n_train
    return metrics


def train(project_dir: Path, dry_run: bool = False) -> dict:
    if dry_run:
        return dry_run_timing(project_dir)

    config = read_json(project_dir / CONFIG_FILE, default={}) or {}
    data = load_data(project_dir, config)
    task_type = data["task_type"]
    metric = metric_for(project_dir, task_type)
    higher = HIGHER_IS_BETTER[metric]
    n_classes = len(data["classes"]) if data["classes"] is not None else None
    epochs = int(config.get("epochs", 10))
    patience = int(config.get("early_stopping_patience", 0))
    metrics_path = project_dir / METRICS_FILE

    metrics = empty_metrics()
    metrics["started_at"] = datetime.now(timezone.utc).isoformat(timespec="microseconds")
    metrics["model_type"] = str(config.get("model_type", "gradient_boosting"))
    metrics.update({
        "task_type": task_type,
        "metric": metric,
        "higher_is_better": higher,
        "config": config,
        "classes": data["classes"],
        "n_train": int(len(data["X_train"])),
        "n_val": int(len(data["X_val"])),
        "n_test": int(len(data["X_test"])),
    })

    def save() -> None:
        write_json(metrics_path, metrics)

    save()
    model = build_model(config, task_type, data["categorical_mask"])
    best_model = None
    best_value = None
    since_best = 0
    started = time.time()
    for epoch in range(1, epochs + 1):
        t0 = time.time()
        model.fit_epoch(data["X_train"], data["y_train"])
        tr = evaluate_split(model, data["X_train"], data["y_train"], task_type, metric, n_classes)
        va = evaluate_split(model, data["X_val"], data["y_val"], task_type, metric, n_classes)
        row = {
            "epoch": epoch,
            "train_loss": tr["loss"],
            "val_loss": va["loss"],
            "train_metric": tr["value"],
            "val_metric": va["value"],
            "seconds": round(time.time() - t0, 3),
        }
        metrics["epochs"].append(row)
        if not (math.isfinite(row["train_loss"]) and math.isfinite(row["val_loss"])):
            metrics["status"] = "failed"
            metrics["error"] = f"non-finite loss at epoch {epoch}"
            save()
            return metrics
        improved = best_value is None or (
            row["val_metric"] > best_value if higher else row["val_metric"] < best_value
        )
        if improved:
            best_value = row["val_metric"]
            metrics["best_epoch"] = epoch
            metrics["best_val_metric"] = best_value
            best_model = copy.deepcopy(model)
            since_best = 0
        else:
            since_best += 1
        save()
        draw_curves(project_dir, metrics["epochs"], metric)
        print(
            f"epoch {epoch}/{epochs} train_loss={row['train_loss']:.4f} "
            f"val_loss={row['val_loss']:.4f} val_{metric}={row['val_metric']:.4f}",
            flush=True,
        )
        if patience and since_best >= patience:
            metrics["stopped_early"] = True
            break

    elapsed = time.time() - started
    metrics["seconds"] = round(elapsed, 3)
    metrics["seconds_per_epoch"] = round(elapsed / max(1, len(metrics["epochs"])), 4)

    (project_dir / CHECKPOINT).parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(best_model, project_dir / CHECKPOINT)
    metrics["status"] = "done"
    save()
    return metrics


# --- command line ---
def cli_argv() -> list[str]:
    """Arguments when run as a script or via `%run`; nothing under a bare kernel cell.

    A Jupyter/Colab kernel sets `sys.argv[0]` to its own launcher (e.g.
    `ipykernel_launcher.py` or Colab's `colab_kernel_launcher.py`), which also ends in
    `.py`, so checking the extension alone would treat the kernel's own
    `-f <connection-file>.json` flags as ours and crash `argparse`. `%run script.py --flag`
    is different: there argv[0] is this script's own name, not the launcher, so its flags
    are still parsed.
    """
    name = Path(sys.argv[0]).name.lower() if sys.argv else ""
    return sys.argv[1:] if name == SCRIPT_NAME.lower() else []


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Train the model and record every epoch.")
    parser.add_argument("--project", default=".", help="project folder (default: cwd)")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args(argv)
    project_dir = Path(args.project).resolve()
    try:
        if not args.dry_run:
            # Fresh placeholders before training starts, so a failure before the first
            # save() cannot leave a previous run's epochs/best metric on disk.
            write_json(project_dir / METRICS_FILE, empty_metrics())
        metrics = train(project_dir, dry_run=args.dry_run)
        return 0 if metrics["status"] != "failed" else 1
    except Exception as exc:  # noqa: BLE001 - record any failure for the debrief
        traceback.print_exc()
        if not args.dry_run:
            read_metrics = read_json(project_dir / METRICS_FILE, default=None) or {}
            existing = {**empty_metrics(), **read_metrics}
            existing["status"] = "failed"
            existing["error"] = f"{type(exc).__name__}: {exc}"
            write_json(project_dir / METRICS_FILE, existing)
        else:
            print(f"error: {exc}", flush=True)
        return 1


if __name__ == "__main__":
    code = main(cli_argv())
    if code:
        sys.exit(code)
